// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIClientRepository creates a new instance of MockIClientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIClientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIClientRepository {
	mock := &MockIClientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIClientRepository is an autogenerated mock type for the IClientRepository type
type MockIClientRepository struct {
	mock.Mock
}

type MockIClientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIClientRepository) EXPECT() *MockIClientRepository_Expecter {
	return &MockIClientRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIClientRepository
func (_mock *MockIClientRepository) Create(ctx context.Context, model1 *model.Client) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Client) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIClientRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIClientRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.Client
func (_e *MockIClientRepository_Expecter) Create(ctx any, model1 any) *MockIClientRepository_Create_Call {
	return &MockIClientRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockIClientRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.Client)) *MockIClientRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Client
		if args[1] != nil {
			arg1 = args[1].(*model.Client)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIClientRepository_Create_Call) Return(err error) *MockIClientRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIClientRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.Client) error) *MockIClientRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByCode provides a mock function for the type MockIClientRepository
func (_mock *MockIClientRepository) DeleteByCode(ctx context.Context, code string) error {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIClientRepository_DeleteByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByCode'
type MockIClientRepository_DeleteByCode_Call struct {
	*mock.Call
}

// DeleteByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockIClientRepository_Expecter) DeleteByCode(ctx any, code any) *MockIClientRepository_DeleteByCode_Call {
	return &MockIClientRepository_DeleteByCode_Call{Call: _e.mock.On("DeleteByCode", ctx, code)}
}

func (_c *MockIClientRepository_DeleteByCode_Call) Run(run func(ctx context.Context, code string)) *MockIClientRepository_DeleteByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIClientRepository_DeleteByCode_Call) Return(err error) *MockIClientRepository_DeleteByCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIClientRepository_DeleteByCode_Call) RunAndReturn(run func(ctx context.Context, code string) error) *MockIClientRepository_DeleteByCode_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockIClientRepository
func (_mock *MockIClientRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIClientRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIClientRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIClientRepository_Expecter) DeleteByID(ctx any, id any) *MockIClientRepository_DeleteByID_Call {
	return &MockIClientRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockIClientRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockIClientRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIClientRepository_DeleteByID_Call) Return(err error) *MockIClientRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIClientRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIClientRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockIClientRepository
func (_mock *MockIClientRepository) Filter(ctx context.Context, filter1 *filter.Options[model.Client]) (*page.Paginated[model.Client], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.Client]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.Client]) (*page.Paginated[model.Client], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.Client]) *page.Paginated[model.Client]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.Client])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.Client]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIClientRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockIClientRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.Client]
func (_e *MockIClientRepository_Expecter) Filter(ctx any, filter1 any) *MockIClientRepository_Filter_Call {
	return &MockIClientRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockIClientRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.Client])) *MockIClientRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.Client]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.Client])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIClientRepository_Filter_Call) Return(paginated *page.Paginated[model.Client], err error) *MockIClientRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIClientRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.Client]) (*page.Paginated[model.Client], error)) *MockIClientRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function for the type MockIClientRepository
func (_mock *MockIClientRepository) FindByCode(ctx context.Context, code string) (*model.Client, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *model.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Client, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Client); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIClientRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockIClientRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockIClientRepository_Expecter) FindByCode(ctx any, code any) *MockIClientRepository_FindByCode_Call {
	return &MockIClientRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, code)}
}

func (_c *MockIClientRepository_FindByCode_Call) Run(run func(ctx context.Context, code string)) *MockIClientRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIClientRepository_FindByCode_Call) Return(client *model.Client, err error) *MockIClientRepository_FindByCode_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockIClientRepository_FindByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*model.Client, error)) *MockIClientRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIClientRepository
func (_mock *MockIClientRepository) FindByID(ctx context.Context, id string) (*model.Client, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Client, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Client); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIClientRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIClientRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIClientRepository_Expecter) FindByID(ctx any, id any) *MockIClientRepository_FindByID_Call {
	return &MockIClientRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIClientRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockIClientRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIClientRepository_FindByID_Call) Return(client *model.Client, err error) *MockIClientRepository_FindByID_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockIClientRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Client, error)) *MockIClientRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByCode provides a mock function for the type MockIClientRepository
func (_mock *MockIClientRepository) UpdateByCode(ctx context.Context, code string, updates *model.Client) error {
	ret := _mock.Called(ctx, code, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.Client) error); ok {
		r0 = returnFunc(ctx, code, updates)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIClientRepository_UpdateByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByCode'
type MockIClientRepository_UpdateByCode_Call struct {
	*mock.Call
}

// UpdateByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - updates *model.Client
func (_e *MockIClientRepository_Expecter) UpdateByCode(ctx any, code any, updates any) *MockIClientRepository_UpdateByCode_Call {
	return &MockIClientRepository_UpdateByCode_Call{Call: _e.mock.On("UpdateByCode", ctx, code, updates)}
}

func (_c *MockIClientRepository_UpdateByCode_Call) Run(run func(ctx context.Context, code string, updates *model.Client)) *MockIClientRepository_UpdateByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.Client
		if args[2] != nil {
			arg2 = args[2].(*model.Client)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIClientRepository_UpdateByCode_Call) Return(err error) *MockIClientRepository_UpdateByCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIClientRepository_UpdateByCode_Call) RunAndReturn(run func(ctx context.Context, code string, updates *model.Client) error) *MockIClientRepository_UpdateByCode_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockIClientRepository
func (_mock *MockIClientRepository) UpdateByID(ctx context.Context, id string, model1 *model.Client) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.Client) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIClientRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockIClientRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.Client
func (_e *MockIClientRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockIClientRepository_UpdateByID_Call {
	return &MockIClientRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockIClientRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.Client)) *MockIClientRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.Client
		if args[2] != nil {
			arg2 = args[2].(*model.Client)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIClientRepository_UpdateByID_Call) Return(err error) *MockIClientRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIClientRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.Client) error) *MockIClientRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
