// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIIndexedKnowledgeItemRepository creates a new instance of MockIIndexedKnowledgeItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIIndexedKnowledgeItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIIndexedKnowledgeItemRepository {
	mock := &MockIIndexedKnowledgeItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIIndexedKnowledgeItemRepository is an autogenerated mock type for the IIndexedKnowledgeItemRepository type
type MockIIndexedKnowledgeItemRepository struct {
	mock.Mock
}

type MockIIndexedKnowledgeItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIIndexedKnowledgeItemRepository) EXPECT() *MockIIndexedKnowledgeItemRepository_Expecter {
	return &MockIIndexedKnowledgeItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) Create(ctx context.Context, model1 *model.IndexedKnowledgeItem) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.IndexedKnowledgeItem) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIIndexedKnowledgeItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIIndexedKnowledgeItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.IndexedKnowledgeItem
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) Create(ctx any, model1 any) *MockIIndexedKnowledgeItemRepository_Create_Call {
	return &MockIIndexedKnowledgeItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockIIndexedKnowledgeItemRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.IndexedKnowledgeItem)) *MockIIndexedKnowledgeItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.IndexedKnowledgeItem
		if args[1] != nil {
			arg1 = args[1].(*model.IndexedKnowledgeItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_Create_Call) Return(err error) *MockIIndexedKnowledgeItemRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.IndexedKnowledgeItem) error) *MockIIndexedKnowledgeItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIIndexedKnowledgeItemRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIIndexedKnowledgeItemRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) DeleteByID(ctx any, id any) *MockIIndexedKnowledgeItemRepository_DeleteByID_Call {
	return &MockIIndexedKnowledgeItemRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockIIndexedKnowledgeItemRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockIIndexedKnowledgeItemRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_DeleteByID_Call) Return(err error) *MockIIndexedKnowledgeItemRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIIndexedKnowledgeItemRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) Filter(ctx context.Context, filter1 *filter.Options[model.IndexedKnowledgeItem]) (*page.Paginated[model.IndexedKnowledgeItem], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.IndexedKnowledgeItem]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.IndexedKnowledgeItem]) (*page.Paginated[model.IndexedKnowledgeItem], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.IndexedKnowledgeItem]) *page.Paginated[model.IndexedKnowledgeItem]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.IndexedKnowledgeItem])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.IndexedKnowledgeItem]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIIndexedKnowledgeItemRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockIIndexedKnowledgeItemRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.IndexedKnowledgeItem]
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) Filter(ctx any, filter1 any) *MockIIndexedKnowledgeItemRepository_Filter_Call {
	return &MockIIndexedKnowledgeItemRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockIIndexedKnowledgeItemRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.IndexedKnowledgeItem])) *MockIIndexedKnowledgeItemRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.IndexedKnowledgeItem]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.IndexedKnowledgeItem])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_Filter_Call) Return(paginated *page.Paginated[model.IndexedKnowledgeItem], err error) *MockIIndexedKnowledgeItemRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.IndexedKnowledgeItem]) (*page.Paginated[model.IndexedKnowledgeItem], error)) *MockIIndexedKnowledgeItemRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) FindByID(ctx context.Context, id string) (*model.IndexedKnowledgeItem, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.IndexedKnowledgeItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.IndexedKnowledgeItem, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.IndexedKnowledgeItem); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.IndexedKnowledgeItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIIndexedKnowledgeItemRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIIndexedKnowledgeItemRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) FindByID(ctx any, id any) *MockIIndexedKnowledgeItemRepository_FindByID_Call {
	return &MockIIndexedKnowledgeItemRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIIndexedKnowledgeItemRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockIIndexedKnowledgeItemRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_FindByID_Call) Return(indexedKnowledgeItem *model.IndexedKnowledgeItem, err error) *MockIIndexedKnowledgeItemRepository_FindByID_Call {
	_c.Call.Return(indexedKnowledgeItem, err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.IndexedKnowledgeItem, error)) *MockIIndexedKnowledgeItemRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) UpdateByID(ctx context.Context, id string, model1 *model.IndexedKnowledgeItem) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.IndexedKnowledgeItem) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIIndexedKnowledgeItemRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockIIndexedKnowledgeItemRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.IndexedKnowledgeItem
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockIIndexedKnowledgeItemRepository_UpdateByID_Call {
	return &MockIIndexedKnowledgeItemRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockIIndexedKnowledgeItemRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.IndexedKnowledgeItem)) *MockIIndexedKnowledgeItemRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.IndexedKnowledgeItem
		if args[2] != nil {
			arg2 = args[2].(*model.IndexedKnowledgeItem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_UpdateByID_Call) Return(err error) *MockIIndexedKnowledgeItemRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.IndexedKnowledgeItem) error) *MockIIndexedKnowledgeItemRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
