root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build"
  entrypoint = ["./tmp/api"]
  include_ext = ["go", ".env"]
  exclude_dir = ["tmp", "vendor", ".git"]
  delay = 300
  send_interrupt = true
  kill_delay = 15000
