// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/runtime"
	"github.com/usesnipet/snipet/internal/util"
)

// NewMockISourceDriver creates a new instance of MockISourceDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISourceDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISourceDriver {
	mock := &MockISourceDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockISourceDriver is an autogenerated mock type for the ISourceDriver type
type MockISourceDriver struct {
	mock.Mock
}

type MockISourceDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISourceDriver) EXPECT() *MockISourceDriver_Expecter {
	return &MockISourceDriver_Expecter{mock: &_m.Mock}
}

// GetConfigurationSchema provides a mock function for the type MockISourceDriver
func (_mock *MockISourceDriver) GetConfigurationSchema(ctx context.Context) (util.JSONMap, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigurationSchema")
	}

	var r0 util.JSONMap
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (util.JSONMap, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) util.JSONMap); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(util.JSONMap)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISourceDriver_GetConfigurationSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigurationSchema'
type MockISourceDriver_GetConfigurationSchema_Call struct {
	*mock.Call
}

// GetConfigurationSchema is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockISourceDriver_Expecter) GetConfigurationSchema(ctx any) *MockISourceDriver_GetConfigurationSchema_Call {
	return &MockISourceDriver_GetConfigurationSchema_Call{Call: _e.mock.On("GetConfigurationSchema", ctx)}
}

func (_c *MockISourceDriver_GetConfigurationSchema_Call) Run(run func(ctx context.Context)) *MockISourceDriver_GetConfigurationSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockISourceDriver_GetConfigurationSchema_Call) Return(jSONMap util.JSONMap, err error) *MockISourceDriver_GetConfigurationSchema_Call {
	_c.Call.Return(jSONMap, err)
	return _c
}

func (_c *MockISourceDriver_GetConfigurationSchema_Call) RunAndReturn(run func(ctx context.Context) (util.JSONMap, error)) *MockISourceDriver_GetConfigurationSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetContent provides a mock function for the type MockISourceDriver
func (_mock *MockISourceDriver) GetContent(ctx context.Context, itemID string) (runtime.IContent, error) {
	ret := _mock.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetContent")
	}

	var r0 runtime.IContent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (runtime.IContent, error)); ok {
		return returnFunc(ctx, itemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) runtime.IContent); ok {
		r0 = returnFunc(ctx, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(runtime.IContent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISourceDriver_GetContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContent'
type MockISourceDriver_GetContent_Call struct {
	*mock.Call
}

// GetContent is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID string
func (_e *MockISourceDriver_Expecter) GetContent(ctx any, itemID any) *MockISourceDriver_GetContent_Call {
	return &MockISourceDriver_GetContent_Call{Call: _e.mock.On("GetContent", ctx, itemID)}
}

func (_c *MockISourceDriver_GetContent_Call) Run(run func(ctx context.Context, itemID string)) *MockISourceDriver_GetContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISourceDriver_GetContent_Call) Return(iContent runtime.IContent, err error) *MockISourceDriver_GetContent_Call {
	_c.Call.Return(iContent, err)
	return _c
}

func (_c *MockISourceDriver_GetContent_Call) RunAndReturn(run func(ctx context.Context, itemID string) (runtime.IContent, error)) *MockISourceDriver_GetContent_Call {
	_c.Call.Return(run)
	return _c
}

// Iterator provides a mock function for the type MockISourceDriver
func (_mock *MockISourceDriver) Iterator(ctx context.Context, config util.JSONMap) (runtime.ISourceIterator, error) {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for Iterator")
	}

	var r0 runtime.ISourceIterator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap) (runtime.ISourceIterator, error)); ok {
		return returnFunc(ctx, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap) runtime.ISourceIterator); ok {
		r0 = returnFunc(ctx, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(runtime.ISourceIterator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, util.JSONMap) error); ok {
		r1 = returnFunc(ctx, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISourceDriver_Iterator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Iterator'
type MockISourceDriver_Iterator_Call struct {
	*mock.Call
}

// Iterator is a helper method to define mock.On call
//   - ctx context.Context
//   - config util.JSONMap
func (_e *MockISourceDriver_Expecter) Iterator(ctx any, config any) *MockISourceDriver_Iterator_Call {
	return &MockISourceDriver_Iterator_Call{Call: _e.mock.On("Iterator", ctx, config)}
}

func (_c *MockISourceDriver_Iterator_Call) Run(run func(ctx context.Context, config util.JSONMap)) *MockISourceDriver_Iterator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 util.JSONMap
		if args[1] != nil {
			arg1 = args[1].(util.JSONMap)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISourceDriver_Iterator_Call) Return(iSourceIterator runtime.ISourceIterator, err error) *MockISourceDriver_Iterator_Call {
	_c.Call.Return(iSourceIterator, err)
	return _c
}

func (_c *MockISourceDriver_Iterator_Call) RunAndReturn(run func(ctx context.Context, config util.JSONMap) (runtime.ISourceIterator, error)) *MockISourceDriver_Iterator_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type MockISourceDriver
func (_mock *MockISourceDriver) TestConnection(ctx context.Context, config util.JSONMap) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockISourceDriver_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockISourceDriver_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - config util.JSONMap
func (_e *MockISourceDriver_Expecter) TestConnection(ctx any, config any) *MockISourceDriver_TestConnection_Call {
	return &MockISourceDriver_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx, config)}
}

func (_c *MockISourceDriver_TestConnection_Call) Run(run func(ctx context.Context, config util.JSONMap)) *MockISourceDriver_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 util.JSONMap
		if args[1] != nil {
			arg1 = args[1].(util.JSONMap)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISourceDriver_TestConnection_Call) Return(err error) *MockISourceDriver_TestConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockISourceDriver_TestConnection_Call) RunAndReturn(run func(ctx context.Context, config util.JSONMap) error) *MockISourceDriver_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}
