// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIAccountRepository creates a new instance of MockIAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAccountRepository {
	mock := &MockIAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAccountRepository is an autogenerated mock type for the IAccountRepository type
type MockIAccountRepository struct {
	mock.Mock
}

type MockIAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAccountRepository) EXPECT() *MockIAccountRepository_Expecter {
	return &MockIAccountRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIAccountRepository
func (_mock *MockIAccountRepository) Create(ctx context.Context, model1 *model.Account) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.Account
func (_e *MockIAccountRepository_Expecter) Create(ctx any, model1 any) *MockIAccountRepository_Create_Call {
	return &MockIAccountRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockIAccountRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.Account)) *MockIAccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Account
		if args[1] != nil {
			arg1 = args[1].(*model.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountRepository_Create_Call) Return(err error) *MockIAccountRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAccountRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.Account) error) *MockIAccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockIAccountRepository
func (_mock *MockIAccountRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAccountRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIAccountRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAccountRepository_Expecter) DeleteByID(ctx any, id any) *MockIAccountRepository_DeleteByID_Call {
	return &MockIAccountRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockIAccountRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockIAccountRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountRepository_DeleteByID_Call) Return(err error) *MockIAccountRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAccountRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIAccountRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockIAccountRepository
func (_mock *MockIAccountRepository) Filter(ctx context.Context, filter1 *filter.Options[model.Account]) (*page.Paginated[model.Account], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.Account]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.Account]) (*page.Paginated[model.Account], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.Account]) *page.Paginated[model.Account]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.Account])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.Account]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockIAccountRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.Account]
func (_e *MockIAccountRepository_Expecter) Filter(ctx any, filter1 any) *MockIAccountRepository_Filter_Call {
	return &MockIAccountRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockIAccountRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.Account])) *MockIAccountRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.Account]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.Account])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountRepository_Filter_Call) Return(paginated *page.Paginated[model.Account], err error) *MockIAccountRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIAccountRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.Account]) (*page.Paginated[model.Account], error)) *MockIAccountRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIAccountRepository
func (_mock *MockIAccountRepository) FindByID(ctx context.Context, id string) (*model.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIAccountRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAccountRepository_Expecter) FindByID(ctx any, id any) *MockIAccountRepository_FindByID_Call {
	return &MockIAccountRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIAccountRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockIAccountRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountRepository_FindByID_Call) Return(account *model.Account, err error) *MockIAccountRepository_FindByID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockIAccountRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Account, error)) *MockIAccountRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByProviderAndExternalID provides a mock function for the type MockIAccountRepository
func (_mock *MockIAccountRepository) FindByProviderAndExternalID(ctx context.Context, provider string, externalID string) (*model.Account, error) {
	ret := _mock.Called(ctx, provider, externalID)

	if len(ret) == 0 {
		panic("no return value specified for FindByProviderAndExternalID")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Account, error)); ok {
		return returnFunc(ctx, provider, externalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Account); ok {
		r0 = returnFunc(ctx, provider, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, externalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountRepository_FindByProviderAndExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByProviderAndExternalID'
type MockIAccountRepository_FindByProviderAndExternalID_Call struct {
	*mock.Call
}

// FindByProviderAndExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - externalID string
func (_e *MockIAccountRepository_Expecter) FindByProviderAndExternalID(ctx any, provider any, externalID any) *MockIAccountRepository_FindByProviderAndExternalID_Call {
	return &MockIAccountRepository_FindByProviderAndExternalID_Call{Call: _e.mock.On("FindByProviderAndExternalID", ctx, provider, externalID)}
}

func (_c *MockIAccountRepository_FindByProviderAndExternalID_Call) Run(run func(ctx context.Context, provider string, externalID string)) *MockIAccountRepository_FindByProviderAndExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAccountRepository_FindByProviderAndExternalID_Call) Return(account *model.Account, err error) *MockIAccountRepository_FindByProviderAndExternalID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockIAccountRepository_FindByProviderAndExternalID_Call) RunAndReturn(run func(ctx context.Context, provider string, externalID string) (*model.Account, error)) *MockIAccountRepository_FindByProviderAndExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockIAccountRepository
func (_mock *MockIAccountRepository) UpdateByID(ctx context.Context, id string, model1 *model.Account) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.Account) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAccountRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockIAccountRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.Account
func (_e *MockIAccountRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockIAccountRepository_UpdateByID_Call {
	return &MockIAccountRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockIAccountRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.Account)) *MockIAccountRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.Account
		if args[2] != nil {
			arg2 = args[2].(*model.Account)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAccountRepository_UpdateByID_Call) Return(err error) *MockIAccountRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAccountRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.Account) error) *MockIAccountRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
