// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIApiKeyRepository creates a new instance of MockIApiKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIApiKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIApiKeyRepository {
	mock := &MockIApiKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIApiKeyRepository is an autogenerated mock type for the IApiKeyRepository type
type MockIApiKeyRepository struct {
	mock.Mock
}

type MockIApiKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIApiKeyRepository) EXPECT() *MockIApiKeyRepository_Expecter {
	return &MockIApiKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIApiKeyRepository
func (_mock *MockIApiKeyRepository) Create(ctx context.Context, model1 *model.APIKey) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.APIKey) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIApiKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIApiKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.APIKey
func (_e *MockIApiKeyRepository_Expecter) Create(ctx any, model1 any) *MockIApiKeyRepository_Create_Call {
	return &MockIApiKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockIApiKeyRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.APIKey)) *MockIApiKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.APIKey
		if args[1] != nil {
			arg1 = args[1].(*model.APIKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIApiKeyRepository_Create_Call) Return(err error) *MockIApiKeyRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIApiKeyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.APIKey) error) *MockIApiKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockIApiKeyRepository
func (_mock *MockIApiKeyRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIApiKeyRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIApiKeyRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIApiKeyRepository_Expecter) DeleteByID(ctx any, id any) *MockIApiKeyRepository_DeleteByID_Call {
	return &MockIApiKeyRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockIApiKeyRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockIApiKeyRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIApiKeyRepository_DeleteByID_Call) Return(err error) *MockIApiKeyRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIApiKeyRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIApiKeyRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockIApiKeyRepository
func (_mock *MockIApiKeyRepository) Filter(ctx context.Context, filter1 *filter.Options[model.APIKey]) (*page.Paginated[model.APIKey], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.APIKey]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.APIKey]) (*page.Paginated[model.APIKey], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.APIKey]) *page.Paginated[model.APIKey]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.APIKey])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.APIKey]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIApiKeyRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockIApiKeyRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.APIKey]
func (_e *MockIApiKeyRepository_Expecter) Filter(ctx any, filter1 any) *MockIApiKeyRepository_Filter_Call {
	return &MockIApiKeyRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockIApiKeyRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.APIKey])) *MockIApiKeyRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.APIKey]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.APIKey])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIApiKeyRepository_Filter_Call) Return(paginated *page.Paginated[model.APIKey], err error) *MockIApiKeyRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIApiKeyRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.APIKey]) (*page.Paginated[model.APIKey], error)) *MockIApiKeyRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIApiKeyRepository
func (_mock *MockIApiKeyRepository) FindByID(ctx context.Context, id string) (*model.APIKey, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.APIKey, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.APIKey); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIApiKeyRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIApiKeyRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIApiKeyRepository_Expecter) FindByID(ctx any, id any) *MockIApiKeyRepository_FindByID_Call {
	return &MockIApiKeyRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIApiKeyRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockIApiKeyRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIApiKeyRepository_FindByID_Call) Return(aPIKey *model.APIKey, err error) *MockIApiKeyRepository_FindByID_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockIApiKeyRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.APIKey, error)) *MockIApiKeyRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleActive provides a mock function for the type MockIApiKeyRepository
func (_mock *MockIApiKeyRepository) ToggleActive(ctx context.Context, tenantID string, id string, active bool) error {
	ret := _mock.Called(ctx, tenantID, id, active)

	if len(ret) == 0 {
		panic("no return value specified for ToggleActive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = returnFunc(ctx, tenantID, id, active)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIApiKeyRepository_ToggleActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleActive'
type MockIApiKeyRepository_ToggleActive_Call struct {
	*mock.Call
}

// ToggleActive is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
//   - active bool
func (_e *MockIApiKeyRepository_Expecter) ToggleActive(ctx any, tenantID any, id any, active any) *MockIApiKeyRepository_ToggleActive_Call {
	return &MockIApiKeyRepository_ToggleActive_Call{Call: _e.mock.On("ToggleActive", ctx, tenantID, id, active)}
}

func (_c *MockIApiKeyRepository_ToggleActive_Call) Run(run func(ctx context.Context, tenantID string, id string, active bool)) *MockIApiKeyRepository_ToggleActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIApiKeyRepository_ToggleActive_Call) Return(err error) *MockIApiKeyRepository_ToggleActive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIApiKeyRepository_ToggleActive_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string, active bool) error) *MockIApiKeyRepository_ToggleActive_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockIApiKeyRepository
func (_mock *MockIApiKeyRepository) UpdateByID(ctx context.Context, id string, model1 *model.APIKey) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.APIKey) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIApiKeyRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockIApiKeyRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.APIKey
func (_e *MockIApiKeyRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockIApiKeyRepository_UpdateByID_Call {
	return &MockIApiKeyRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockIApiKeyRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.APIKey)) *MockIApiKeyRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.APIKey
		if args[2] != nil {
			arg2 = args[2].(*model.APIKey)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIApiKeyRepository_UpdateByID_Call) Return(err error) *MockIApiKeyRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIApiKeyRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.APIKey) error) *MockIApiKeyRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExpiration provides a mock function for the type MockIApiKeyRepository
func (_mock *MockIApiKeyRepository) UpdateExpiration(ctx context.Context, tenantID string, id string, expiresAt *time.Time) error {
	ret := _mock.Called(ctx, tenantID, id, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExpiration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *time.Time) error); ok {
		r0 = returnFunc(ctx, tenantID, id, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIApiKeyRepository_UpdateExpiration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExpiration'
type MockIApiKeyRepository_UpdateExpiration_Call struct {
	*mock.Call
}

// UpdateExpiration is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - id string
//   - expiresAt *time.Time
func (_e *MockIApiKeyRepository_Expecter) UpdateExpiration(ctx any, tenantID any, id any, expiresAt any) *MockIApiKeyRepository_UpdateExpiration_Call {
	return &MockIApiKeyRepository_UpdateExpiration_Call{Call: _e.mock.On("UpdateExpiration", ctx, tenantID, id, expiresAt)}
}

func (_c *MockIApiKeyRepository_UpdateExpiration_Call) Run(run func(ctx context.Context, tenantID string, id string, expiresAt *time.Time)) *MockIApiKeyRepository_UpdateExpiration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIApiKeyRepository_UpdateExpiration_Call) Return(err error) *MockIApiKeyRepository_UpdateExpiration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIApiKeyRepository_UpdateExpiration_Call) RunAndReturn(run func(ctx context.Context, tenantID string, id string, expiresAt *time.Time) error) *MockIApiKeyRepository_UpdateExpiration_Call {
	_c.Call.Return(run)
	return _c
}
