// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIAppRepository creates a new instance of MockIAppRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAppRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAppRepository {
	mock := &MockIAppRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAppRepository is an autogenerated mock type for the IAppRepository type
type MockIAppRepository struct {
	mock.Mock
}

type MockIAppRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAppRepository) EXPECT() *MockIAppRepository_Expecter {
	return &MockIAppRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIAppRepository
func (_mock *MockIAppRepository) Create(ctx context.Context, model1 *model.App) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.App) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAppRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAppRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.App
func (_e *MockIAppRepository_Expecter) Create(ctx any, model1 any) *MockIAppRepository_Create_Call {
	return &MockIAppRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockIAppRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.App)) *MockIAppRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.App
		if args[1] != nil {
			arg1 = args[1].(*model.App)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAppRepository_Create_Call) Return(err error) *MockIAppRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAppRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.App) error) *MockIAppRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByCode provides a mock function for the type MockIAppRepository
func (_mock *MockIAppRepository) DeleteByCode(ctx context.Context, code string) error {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAppRepository_DeleteByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByCode'
type MockIAppRepository_DeleteByCode_Call struct {
	*mock.Call
}

// DeleteByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockIAppRepository_Expecter) DeleteByCode(ctx any, code any) *MockIAppRepository_DeleteByCode_Call {
	return &MockIAppRepository_DeleteByCode_Call{Call: _e.mock.On("DeleteByCode", ctx, code)}
}

func (_c *MockIAppRepository_DeleteByCode_Call) Run(run func(ctx context.Context, code string)) *MockIAppRepository_DeleteByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAppRepository_DeleteByCode_Call) Return(err error) *MockIAppRepository_DeleteByCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAppRepository_DeleteByCode_Call) RunAndReturn(run func(ctx context.Context, code string) error) *MockIAppRepository_DeleteByCode_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockIAppRepository
func (_mock *MockIAppRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAppRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIAppRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAppRepository_Expecter) DeleteByID(ctx any, id any) *MockIAppRepository_DeleteByID_Call {
	return &MockIAppRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockIAppRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockIAppRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAppRepository_DeleteByID_Call) Return(err error) *MockIAppRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAppRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIAppRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockIAppRepository
func (_mock *MockIAppRepository) Filter(ctx context.Context, filter1 *filter.Options[model.App]) (*page.Paginated[model.App], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.App]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.App]) (*page.Paginated[model.App], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.App]) *page.Paginated[model.App]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.App])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.App]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAppRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockIAppRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.App]
func (_e *MockIAppRepository_Expecter) Filter(ctx any, filter1 any) *MockIAppRepository_Filter_Call {
	return &MockIAppRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockIAppRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.App])) *MockIAppRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.App]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.App])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAppRepository_Filter_Call) Return(paginated *page.Paginated[model.App], err error) *MockIAppRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIAppRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.App]) (*page.Paginated[model.App], error)) *MockIAppRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function for the type MockIAppRepository
func (_mock *MockIAppRepository) FindByCode(ctx context.Context, code string) (*model.App, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *model.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.App, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.App); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAppRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockIAppRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockIAppRepository_Expecter) FindByCode(ctx any, code any) *MockIAppRepository_FindByCode_Call {
	return &MockIAppRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, code)}
}

func (_c *MockIAppRepository_FindByCode_Call) Run(run func(ctx context.Context, code string)) *MockIAppRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAppRepository_FindByCode_Call) Return(app *model.App, err error) *MockIAppRepository_FindByCode_Call {
	_c.Call.Return(app, err)
	return _c
}

func (_c *MockIAppRepository_FindByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*model.App, error)) *MockIAppRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIAppRepository
func (_mock *MockIAppRepository) FindByID(ctx context.Context, id string) (*model.App, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.App, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.App); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAppRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIAppRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAppRepository_Expecter) FindByID(ctx any, id any) *MockIAppRepository_FindByID_Call {
	return &MockIAppRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIAppRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockIAppRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAppRepository_FindByID_Call) Return(app *model.App, err error) *MockIAppRepository_FindByID_Call {
	_c.Call.Return(app, err)
	return _c
}

func (_c *MockIAppRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.App, error)) *MockIAppRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAuthConfigByCode provides a mock function for the type MockIAppRepository
func (_mock *MockIAppRepository) UpdateAuthConfigByCode(ctx context.Context, code string, authConfig model.AppAuthConfig) error {
	ret := _mock.Called(ctx, code, authConfig)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAuthConfigByCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.AppAuthConfig) error); ok {
		r0 = returnFunc(ctx, code, authConfig)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAppRepository_UpdateAuthConfigByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAuthConfigByCode'
type MockIAppRepository_UpdateAuthConfigByCode_Call struct {
	*mock.Call
}

// UpdateAuthConfigByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - authConfig model.AppAuthConfig
func (_e *MockIAppRepository_Expecter) UpdateAuthConfigByCode(ctx any, code any, authConfig any) *MockIAppRepository_UpdateAuthConfigByCode_Call {
	return &MockIAppRepository_UpdateAuthConfigByCode_Call{Call: _e.mock.On("UpdateAuthConfigByCode", ctx, code, authConfig)}
}

func (_c *MockIAppRepository_UpdateAuthConfigByCode_Call) Run(run func(ctx context.Context, code string, authConfig model.AppAuthConfig)) *MockIAppRepository_UpdateAuthConfigByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.AppAuthConfig
		if args[2] != nil {
			arg2 = args[2].(model.AppAuthConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAppRepository_UpdateAuthConfigByCode_Call) Return(err error) *MockIAppRepository_UpdateAuthConfigByCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAppRepository_UpdateAuthConfigByCode_Call) RunAndReturn(run func(ctx context.Context, code string, authConfig model.AppAuthConfig) error) *MockIAppRepository_UpdateAuthConfigByCode_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByCode provides a mock function for the type MockIAppRepository
func (_mock *MockIAppRepository) UpdateByCode(ctx context.Context, code string, updates *model.App) error {
	ret := _mock.Called(ctx, code, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.App) error); ok {
		r0 = returnFunc(ctx, code, updates)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAppRepository_UpdateByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByCode'
type MockIAppRepository_UpdateByCode_Call struct {
	*mock.Call
}

// UpdateByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - updates *model.App
func (_e *MockIAppRepository_Expecter) UpdateByCode(ctx any, code any, updates any) *MockIAppRepository_UpdateByCode_Call {
	return &MockIAppRepository_UpdateByCode_Call{Call: _e.mock.On("UpdateByCode", ctx, code, updates)}
}

func (_c *MockIAppRepository_UpdateByCode_Call) Run(run func(ctx context.Context, code string, updates *model.App)) *MockIAppRepository_UpdateByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.App
		if args[2] != nil {
			arg2 = args[2].(*model.App)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAppRepository_UpdateByCode_Call) Return(err error) *MockIAppRepository_UpdateByCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAppRepository_UpdateByCode_Call) RunAndReturn(run func(ctx context.Context, code string, updates *model.App) error) *MockIAppRepository_UpdateByCode_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockIAppRepository
func (_mock *MockIAppRepository) UpdateByID(ctx context.Context, id string, model1 *model.App) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.App) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAppRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockIAppRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.App
func (_e *MockIAppRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockIAppRepository_UpdateByID_Call {
	return &MockIAppRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockIAppRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.App)) *MockIAppRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.App
		if args[2] != nil {
			arg2 = args[2].(*model.App)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAppRepository_UpdateByID_Call) Return(err error) *MockIAppRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAppRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.App) error) *MockIAppRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePublicByCode provides a mock function for the type MockIAppRepository
func (_mock *MockIAppRepository) UpdatePublicByCode(ctx context.Context, code string, public bool) error {
	ret := _mock.Called(ctx, code, public)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePublicByCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, code, public)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAppRepository_UpdatePublicByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePublicByCode'
type MockIAppRepository_UpdatePublicByCode_Call struct {
	*mock.Call
}

// UpdatePublicByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - public bool
func (_e *MockIAppRepository_Expecter) UpdatePublicByCode(ctx any, code any, public any) *MockIAppRepository_UpdatePublicByCode_Call {
	return &MockIAppRepository_UpdatePublicByCode_Call{Call: _e.mock.On("UpdatePublicByCode", ctx, code, public)}
}

func (_c *MockIAppRepository_UpdatePublicByCode_Call) Run(run func(ctx context.Context, code string, public bool)) *MockIAppRepository_UpdatePublicByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAppRepository_UpdatePublicByCode_Call) Return(err error) *MockIAppRepository_UpdatePublicByCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAppRepository_UpdatePublicByCode_Call) RunAndReturn(run func(ctx context.Context, code string, public bool) error) *MockIAppRepository_UpdatePublicByCode_Call {
	_c.Call.Return(run)
	return _c
}
