// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIAppUserRepository creates a new instance of MockIAppUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAppUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAppUserRepository {
	mock := &MockIAppUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAppUserRepository is an autogenerated mock type for the IAppUserRepository type
type MockIAppUserRepository struct {
	mock.Mock
}

type MockIAppUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAppUserRepository) EXPECT() *MockIAppUserRepository_Expecter {
	return &MockIAppUserRepository_Expecter{mock: &_m.Mock}
}

// CreateInApp provides a mock function for the type MockIAppUserRepository
func (_mock *MockIAppUserRepository) CreateInApp(ctx context.Context, appCode string, user *model.AppUser, externalID *string) error {
	ret := _mock.Called(ctx, appCode, user, externalID)

	if len(ret) == 0 {
		panic("no return value specified for CreateInApp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.AppUser, *string) error); ok {
		r0 = returnFunc(ctx, appCode, user, externalID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAppUserRepository_CreateInApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInApp'
type MockIAppUserRepository_CreateInApp_Call struct {
	*mock.Call
}

// CreateInApp is a helper method to define mock.On call
//   - ctx context.Context
//   - appCode string
//   - user *model.AppUser
//   - externalID *string
func (_e *MockIAppUserRepository_Expecter) CreateInApp(ctx any, appCode any, user any, externalID any) *MockIAppUserRepository_CreateInApp_Call {
	return &MockIAppUserRepository_CreateInApp_Call{Call: _e.mock.On("CreateInApp", ctx, appCode, user, externalID)}
}

func (_c *MockIAppUserRepository_CreateInApp_Call) Run(run func(ctx context.Context, appCode string, user *model.AppUser, externalID *string)) *MockIAppUserRepository_CreateInApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.AppUser
		if args[2] != nil {
			arg2 = args[2].(*model.AppUser)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIAppUserRepository_CreateInApp_Call) Return(err error) *MockIAppUserRepository_CreateInApp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAppUserRepository_CreateInApp_Call) RunAndReturn(run func(ctx context.Context, appCode string, user *model.AppUser, externalID *string) error) *MockIAppUserRepository_CreateInApp_Call {
	_c.Call.Return(run)
	return _c
}

// FilterInApp provides a mock function for the type MockIAppUserRepository
func (_mock *MockIAppUserRepository) FilterInApp(ctx context.Context, appCode string, filter1 *filter.Options[model.AppUser]) (*page.Paginated[model.AppUser], error) {
	ret := _mock.Called(ctx, appCode, filter1)

	if len(ret) == 0 {
		panic("no return value specified for FilterInApp")
	}

	var r0 *page.Paginated[model.AppUser]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *filter.Options[model.AppUser]) (*page.Paginated[model.AppUser], error)); ok {
		return returnFunc(ctx, appCode, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *filter.Options[model.AppUser]) *page.Paginated[model.AppUser]); ok {
		r0 = returnFunc(ctx, appCode, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.AppUser])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *filter.Options[model.AppUser]) error); ok {
		r1 = returnFunc(ctx, appCode, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAppUserRepository_FilterInApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterInApp'
type MockIAppUserRepository_FilterInApp_Call struct {
	*mock.Call
}

// FilterInApp is a helper method to define mock.On call
//   - ctx context.Context
//   - appCode string
//   - filter1 *filter.Options[model.AppUser]
func (_e *MockIAppUserRepository_Expecter) FilterInApp(ctx any, appCode any, filter1 any) *MockIAppUserRepository_FilterInApp_Call {
	return &MockIAppUserRepository_FilterInApp_Call{Call: _e.mock.On("FilterInApp", ctx, appCode, filter1)}
}

func (_c *MockIAppUserRepository_FilterInApp_Call) Run(run func(ctx context.Context, appCode string, filter1 *filter.Options[model.AppUser])) *MockIAppUserRepository_FilterInApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *filter.Options[model.AppUser]
		if args[2] != nil {
			arg2 = args[2].(*filter.Options[model.AppUser])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAppUserRepository_FilterInApp_Call) Return(paginated *page.Paginated[model.AppUser], err error) *MockIAppUserRepository_FilterInApp_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIAppUserRepository_FilterInApp_Call) RunAndReturn(run func(ctx context.Context, appCode string, filter1 *filter.Options[model.AppUser]) (*page.Paginated[model.AppUser], error)) *MockIAppUserRepository_FilterInApp_Call {
	_c.Call.Return(run)
	return _c
}

// FindByExternalIDInApp provides a mock function for the type MockIAppUserRepository
func (_mock *MockIAppUserRepository) FindByExternalIDInApp(ctx context.Context, appCode string, externalID string) (*model.AppUser, error) {
	ret := _mock.Called(ctx, appCode, externalID)

	if len(ret) == 0 {
		panic("no return value specified for FindByExternalIDInApp")
	}

	var r0 *model.AppUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.AppUser, error)); ok {
		return returnFunc(ctx, appCode, externalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.AppUser); ok {
		r0 = returnFunc(ctx, appCode, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AppUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, appCode, externalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAppUserRepository_FindByExternalIDInApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByExternalIDInApp'
type MockIAppUserRepository_FindByExternalIDInApp_Call struct {
	*mock.Call
}

// FindByExternalIDInApp is a helper method to define mock.On call
//   - ctx context.Context
//   - appCode string
//   - externalID string
func (_e *MockIAppUserRepository_Expecter) FindByExternalIDInApp(ctx any, appCode any, externalID any) *MockIAppUserRepository_FindByExternalIDInApp_Call {
	return &MockIAppUserRepository_FindByExternalIDInApp_Call{Call: _e.mock.On("FindByExternalIDInApp", ctx, appCode, externalID)}
}

func (_c *MockIAppUserRepository_FindByExternalIDInApp_Call) Run(run func(ctx context.Context, appCode string, externalID string)) *MockIAppUserRepository_FindByExternalIDInApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAppUserRepository_FindByExternalIDInApp_Call) Return(appUser *model.AppUser, err error) *MockIAppUserRepository_FindByExternalIDInApp_Call {
	_c.Call.Return(appUser, err)
	return _c
}

func (_c *MockIAppUserRepository_FindByExternalIDInApp_Call) RunAndReturn(run func(ctx context.Context, appCode string, externalID string) (*model.AppUser, error)) *MockIAppUserRepository_FindByExternalIDInApp_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDInApp provides a mock function for the type MockIAppUserRepository
func (_mock *MockIAppUserRepository) FindByIDInApp(ctx context.Context, appCode string, id string) (*model.AppUser, error) {
	ret := _mock.Called(ctx, appCode, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDInApp")
	}

	var r0 *model.AppUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.AppUser, error)); ok {
		return returnFunc(ctx, appCode, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.AppUser); ok {
		r0 = returnFunc(ctx, appCode, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AppUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, appCode, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAppUserRepository_FindByIDInApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDInApp'
type MockIAppUserRepository_FindByIDInApp_Call struct {
	*mock.Call
}

// FindByIDInApp is a helper method to define mock.On call
//   - ctx context.Context
//   - appCode string
//   - id string
func (_e *MockIAppUserRepository_Expecter) FindByIDInApp(ctx any, appCode any, id any) *MockIAppUserRepository_FindByIDInApp_Call {
	return &MockIAppUserRepository_FindByIDInApp_Call{Call: _e.mock.On("FindByIDInApp", ctx, appCode, id)}
}

func (_c *MockIAppUserRepository_FindByIDInApp_Call) Run(run func(ctx context.Context, appCode string, id string)) *MockIAppUserRepository_FindByIDInApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAppUserRepository_FindByIDInApp_Call) Return(appUser *model.AppUser, err error) *MockIAppUserRepository_FindByIDInApp_Call {
	_c.Call.Return(appUser, err)
	return _c
}

func (_c *MockIAppUserRepository_FindByIDInApp_Call) RunAndReturn(run func(ctx context.Context, appCode string, id string) (*model.AppUser, error)) *MockIAppUserRepository_FindByIDInApp_Call {
	_c.Call.Return(run)
	return _c
}
