// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/model"
)

// NewMockIAppUserRefreshTokenRepository creates a new instance of MockIAppUserRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAppUserRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAppUserRefreshTokenRepository {
	mock := &MockIAppUserRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAppUserRefreshTokenRepository is an autogenerated mock type for the IAppUserRefreshTokenRepository type
type MockIAppUserRefreshTokenRepository struct {
	mock.Mock
}

type MockIAppUserRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAppUserRefreshTokenRepository) EXPECT() *MockIAppUserRefreshTokenRepository_Expecter {
	return &MockIAppUserRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIAppUserRefreshTokenRepository
func (_mock *MockIAppUserRefreshTokenRepository) Create(ctx context.Context, token *model.AppUserRefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AppUserRefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAppUserRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAppUserRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *model.AppUserRefreshToken
func (_e *MockIAppUserRefreshTokenRepository_Expecter) Create(ctx any, token any) *MockIAppUserRefreshTokenRepository_Create_Call {
	return &MockIAppUserRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockIAppUserRefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, token *model.AppUserRefreshToken)) *MockIAppUserRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AppUserRefreshToken
		if args[1] != nil {
			arg1 = args[1].(*model.AppUserRefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAppUserRefreshTokenRepository_Create_Call) Return(err error) *MockIAppUserRefreshTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAppUserRefreshTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, token *model.AppUserRefreshToken) error) *MockIAppUserRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHash provides a mock function for the type MockIAppUserRefreshTokenRepository
func (_mock *MockIAppUserRefreshTokenRepository) FindByHash(ctx context.Context, hash string) (*model.AppUserRefreshToken, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for FindByHash")
	}

	var r0 *model.AppUserRefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.AppUserRefreshToken, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.AppUserRefreshToken); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AppUserRefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAppUserRefreshTokenRepository_FindByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHash'
type MockIAppUserRefreshTokenRepository_FindByHash_Call struct {
	*mock.Call
}

// FindByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockIAppUserRefreshTokenRepository_Expecter) FindByHash(ctx any, hash any) *MockIAppUserRefreshTokenRepository_FindByHash_Call {
	return &MockIAppUserRefreshTokenRepository_FindByHash_Call{Call: _e.mock.On("FindByHash", ctx, hash)}
}

func (_c *MockIAppUserRefreshTokenRepository_FindByHash_Call) Run(run func(ctx context.Context, hash string)) *MockIAppUserRefreshTokenRepository_FindByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAppUserRefreshTokenRepository_FindByHash_Call) Return(appUserRefreshToken *model.AppUserRefreshToken, err error) *MockIAppUserRefreshTokenRepository_FindByHash_Call {
	_c.Call.Return(appUserRefreshToken, err)
	return _c
}

func (_c *MockIAppUserRefreshTokenRepository_FindByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*model.AppUserRefreshToken, error)) *MockIAppUserRefreshTokenRepository_FindByHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByID provides a mock function for the type MockIAppUserRefreshTokenRepository
func (_mock *MockIAppUserRefreshTokenRepository) RevokeByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAppUserRefreshTokenRepository_RevokeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByID'
type MockIAppUserRefreshTokenRepository_RevokeByID_Call struct {
	*mock.Call
}

// RevokeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAppUserRefreshTokenRepository_Expecter) RevokeByID(ctx any, id any) *MockIAppUserRefreshTokenRepository_RevokeByID_Call {
	return &MockIAppUserRefreshTokenRepository_RevokeByID_Call{Call: _e.mock.On("RevokeByID", ctx, id)}
}

func (_c *MockIAppUserRefreshTokenRepository_RevokeByID_Call) Run(run func(ctx context.Context, id string)) *MockIAppUserRefreshTokenRepository_RevokeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAppUserRefreshTokenRepository_RevokeByID_Call) Return(err error) *MockIAppUserRefreshTokenRepository_RevokeByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAppUserRefreshTokenRepository_RevokeByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIAppUserRefreshTokenRepository_RevokeByID_Call {
	_c.Call.Return(run)
	return _c
}
