// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/model"
)

// NewMockIExecutionMessageRepository creates a new instance of MockIExecutionMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIExecutionMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIExecutionMessageRepository {
	mock := &MockIExecutionMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIExecutionMessageRepository is an autogenerated mock type for the IExecutionMessageRepository type
type MockIExecutionMessageRepository struct {
	mock.Mock
}

type MockIExecutionMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIExecutionMessageRepository) EXPECT() *MockIExecutionMessageRepository_Expecter {
	return &MockIExecutionMessageRepository_Expecter{mock: &_m.Mock}
}

// CountByExecutionID provides a mock function for the type MockIExecutionMessageRepository
func (_mock *MockIExecutionMessageRepository) CountByExecutionID(ctx context.Context, executionID string) (int64, error) {
	ret := _mock.Called(ctx, executionID)

	if len(ret) == 0 {
		panic("no return value specified for CountByExecutionID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, executionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, executionID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, executionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIExecutionMessageRepository_CountByExecutionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByExecutionID'
type MockIExecutionMessageRepository_CountByExecutionID_Call struct {
	*mock.Call
}

// CountByExecutionID is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
func (_e *MockIExecutionMessageRepository_Expecter) CountByExecutionID(ctx any, executionID any) *MockIExecutionMessageRepository_CountByExecutionID_Call {
	return &MockIExecutionMessageRepository_CountByExecutionID_Call{Call: _e.mock.On("CountByExecutionID", ctx, executionID)}
}

func (_c *MockIExecutionMessageRepository_CountByExecutionID_Call) Run(run func(ctx context.Context, executionID string)) *MockIExecutionMessageRepository_CountByExecutionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIExecutionMessageRepository_CountByExecutionID_Call) Return(n int64, err error) *MockIExecutionMessageRepository_CountByExecutionID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIExecutionMessageRepository_CountByExecutionID_Call) RunAndReturn(run func(ctx context.Context, executionID string) (int64, error)) *MockIExecutionMessageRepository_CountByExecutionID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockIExecutionMessageRepository
func (_mock *MockIExecutionMessageRepository) Create(ctx context.Context, model1 *model.ExecutionMessage) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ExecutionMessage) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIExecutionMessageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIExecutionMessageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.ExecutionMessage
func (_e *MockIExecutionMessageRepository_Expecter) Create(ctx any, model1 any) *MockIExecutionMessageRepository_Create_Call {
	return &MockIExecutionMessageRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockIExecutionMessageRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.ExecutionMessage)) *MockIExecutionMessageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ExecutionMessage
		if args[1] != nil {
			arg1 = args[1].(*model.ExecutionMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIExecutionMessageRepository_Create_Call) Return(err error) *MockIExecutionMessageRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIExecutionMessageRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.ExecutionMessage) error) *MockIExecutionMessageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
