// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIIndexedKnowledgeItemRepository creates a new instance of MockIIndexedKnowledgeItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIIndexedKnowledgeItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIIndexedKnowledgeItemRepository {
	mock := &MockIIndexedKnowledgeItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIIndexedKnowledgeItemRepository is an autogenerated mock type for the IIndexedKnowledgeItemRepository type
type MockIIndexedKnowledgeItemRepository struct {
	mock.Mock
}

type MockIIndexedKnowledgeItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIIndexedKnowledgeItemRepository) EXPECT() *MockIIndexedKnowledgeItemRepository_Expecter {
	return &MockIIndexedKnowledgeItemRepository_Expecter{mock: &_m.Mock}
}

// CreateInIndex provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) CreateInIndex(ctx context.Context, knowledgeID string, indexID string, item *model.IndexedKnowledgeItem) error {
	ret := _mock.Called(ctx, knowledgeID, indexID, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateInIndex")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *model.IndexedKnowledgeItem) error); ok {
		r0 = returnFunc(ctx, knowledgeID, indexID, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIIndexedKnowledgeItemRepository_CreateInIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInIndex'
type MockIIndexedKnowledgeItemRepository_CreateInIndex_Call struct {
	*mock.Call
}

// CreateInIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - indexID string
//   - item *model.IndexedKnowledgeItem
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) CreateInIndex(ctx any, knowledgeID any, indexID any, item any) *MockIIndexedKnowledgeItemRepository_CreateInIndex_Call {
	return &MockIIndexedKnowledgeItemRepository_CreateInIndex_Call{Call: _e.mock.On("CreateInIndex", ctx, knowledgeID, indexID, item)}
}

func (_c *MockIIndexedKnowledgeItemRepository_CreateInIndex_Call) Run(run func(ctx context.Context, knowledgeID string, indexID string, item *model.IndexedKnowledgeItem)) *MockIIndexedKnowledgeItemRepository_CreateInIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *model.IndexedKnowledgeItem
		if args[3] != nil {
			arg3 = args[3].(*model.IndexedKnowledgeItem)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_CreateInIndex_Call) Return(err error) *MockIIndexedKnowledgeItemRepository_CreateInIndex_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_CreateInIndex_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, indexID string, item *model.IndexedKnowledgeItem) error) *MockIIndexedKnowledgeItemRepository_CreateInIndex_Call {
	_c.Call.Return(run)
	return _c
}

// CreateManyInIndex provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) CreateManyInIndex(ctx context.Context, knowledgeID string, indexID string, items []*model.IndexedKnowledgeItem) error {
	ret := _mock.Called(ctx, knowledgeID, indexID, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateManyInIndex")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []*model.IndexedKnowledgeItem) error); ok {
		r0 = returnFunc(ctx, knowledgeID, indexID, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIIndexedKnowledgeItemRepository_CreateManyInIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateManyInIndex'
type MockIIndexedKnowledgeItemRepository_CreateManyInIndex_Call struct {
	*mock.Call
}

// CreateManyInIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - indexID string
//   - items []*model.IndexedKnowledgeItem
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) CreateManyInIndex(ctx any, knowledgeID any, indexID any, items any) *MockIIndexedKnowledgeItemRepository_CreateManyInIndex_Call {
	return &MockIIndexedKnowledgeItemRepository_CreateManyInIndex_Call{Call: _e.mock.On("CreateManyInIndex", ctx, knowledgeID, indexID, items)}
}

func (_c *MockIIndexedKnowledgeItemRepository_CreateManyInIndex_Call) Run(run func(ctx context.Context, knowledgeID string, indexID string, items []*model.IndexedKnowledgeItem)) *MockIIndexedKnowledgeItemRepository_CreateManyInIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []*model.IndexedKnowledgeItem
		if args[3] != nil {
			arg3 = args[3].([]*model.IndexedKnowledgeItem)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_CreateManyInIndex_Call) Return(err error) *MockIIndexedKnowledgeItemRepository_CreateManyInIndex_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_CreateManyInIndex_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, indexID string, items []*model.IndexedKnowledgeItem) error) *MockIIndexedKnowledgeItemRepository_CreateManyInIndex_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByIDsInIndex provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) DeleteByIDsInIndex(ctx context.Context, knowledgeID string, indexID string, ids []string) error {
	ret := _mock.Called(ctx, knowledgeID, indexID, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIDsInIndex")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = returnFunc(ctx, knowledgeID, indexID, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIIndexedKnowledgeItemRepository_DeleteByIDsInIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByIDsInIndex'
type MockIIndexedKnowledgeItemRepository_DeleteByIDsInIndex_Call struct {
	*mock.Call
}

// DeleteByIDsInIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - indexID string
//   - ids []string
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) DeleteByIDsInIndex(ctx any, knowledgeID any, indexID any, ids any) *MockIIndexedKnowledgeItemRepository_DeleteByIDsInIndex_Call {
	return &MockIIndexedKnowledgeItemRepository_DeleteByIDsInIndex_Call{Call: _e.mock.On("DeleteByIDsInIndex", ctx, knowledgeID, indexID, ids)}
}

func (_c *MockIIndexedKnowledgeItemRepository_DeleteByIDsInIndex_Call) Run(run func(ctx context.Context, knowledgeID string, indexID string, ids []string)) *MockIIndexedKnowledgeItemRepository_DeleteByIDsInIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_DeleteByIDsInIndex_Call) Return(err error) *MockIIndexedKnowledgeItemRepository_DeleteByIDsInIndex_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_DeleteByIDsInIndex_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, indexID string, ids []string) error) *MockIIndexedKnowledgeItemRepository_DeleteByIDsInIndex_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInIndex provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) DeleteInIndex(ctx context.Context, knowledgeID string, indexID string, id string) error {
	ret := _mock.Called(ctx, knowledgeID, indexID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInIndex")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, knowledgeID, indexID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIIndexedKnowledgeItemRepository_DeleteInIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInIndex'
type MockIIndexedKnowledgeItemRepository_DeleteInIndex_Call struct {
	*mock.Call
}

// DeleteInIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - indexID string
//   - id string
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) DeleteInIndex(ctx any, knowledgeID any, indexID any, id any) *MockIIndexedKnowledgeItemRepository_DeleteInIndex_Call {
	return &MockIIndexedKnowledgeItemRepository_DeleteInIndex_Call{Call: _e.mock.On("DeleteInIndex", ctx, knowledgeID, indexID, id)}
}

func (_c *MockIIndexedKnowledgeItemRepository_DeleteInIndex_Call) Run(run func(ctx context.Context, knowledgeID string, indexID string, id string)) *MockIIndexedKnowledgeItemRepository_DeleteInIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_DeleteInIndex_Call) Return(err error) *MockIIndexedKnowledgeItemRepository_DeleteInIndex_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_DeleteInIndex_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, indexID string, id string) error) *MockIIndexedKnowledgeItemRepository_DeleteInIndex_Call {
	_c.Call.Return(run)
	return _c
}

// FilterInIndex provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) FilterInIndex(ctx context.Context, knowledgeID string, indexID string, filter1 *filter.Options[model.IndexedKnowledgeItem]) (*page.Paginated[model.IndexedKnowledgeItem], error) {
	ret := _mock.Called(ctx, knowledgeID, indexID, filter1)

	if len(ret) == 0 {
		panic("no return value specified for FilterInIndex")
	}

	var r0 *page.Paginated[model.IndexedKnowledgeItem]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *filter.Options[model.IndexedKnowledgeItem]) (*page.Paginated[model.IndexedKnowledgeItem], error)); ok {
		return returnFunc(ctx, knowledgeID, indexID, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *filter.Options[model.IndexedKnowledgeItem]) *page.Paginated[model.IndexedKnowledgeItem]); ok {
		r0 = returnFunc(ctx, knowledgeID, indexID, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.IndexedKnowledgeItem])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *filter.Options[model.IndexedKnowledgeItem]) error); ok {
		r1 = returnFunc(ctx, knowledgeID, indexID, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIIndexedKnowledgeItemRepository_FilterInIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterInIndex'
type MockIIndexedKnowledgeItemRepository_FilterInIndex_Call struct {
	*mock.Call
}

// FilterInIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - indexID string
//   - filter1 *filter.Options[model.IndexedKnowledgeItem]
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) FilterInIndex(ctx any, knowledgeID any, indexID any, filter1 any) *MockIIndexedKnowledgeItemRepository_FilterInIndex_Call {
	return &MockIIndexedKnowledgeItemRepository_FilterInIndex_Call{Call: _e.mock.On("FilterInIndex", ctx, knowledgeID, indexID, filter1)}
}

func (_c *MockIIndexedKnowledgeItemRepository_FilterInIndex_Call) Run(run func(ctx context.Context, knowledgeID string, indexID string, filter1 *filter.Options[model.IndexedKnowledgeItem])) *MockIIndexedKnowledgeItemRepository_FilterInIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *filter.Options[model.IndexedKnowledgeItem]
		if args[3] != nil {
			arg3 = args[3].(*filter.Options[model.IndexedKnowledgeItem])
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_FilterInIndex_Call) Return(paginated *page.Paginated[model.IndexedKnowledgeItem], err error) *MockIIndexedKnowledgeItemRepository_FilterInIndex_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_FilterInIndex_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, indexID string, filter1 *filter.Options[model.IndexedKnowledgeItem]) (*page.Paginated[model.IndexedKnowledgeItem], error)) *MockIIndexedKnowledgeItemRepository_FilterInIndex_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDInIndex provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) FindByIDInIndex(ctx context.Context, knowledgeID string, indexID string, id string) (*model.IndexedKnowledgeItem, error) {
	ret := _mock.Called(ctx, knowledgeID, indexID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDInIndex")
	}

	var r0 *model.IndexedKnowledgeItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.IndexedKnowledgeItem, error)); ok {
		return returnFunc(ctx, knowledgeID, indexID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *model.IndexedKnowledgeItem); ok {
		r0 = returnFunc(ctx, knowledgeID, indexID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.IndexedKnowledgeItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, knowledgeID, indexID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIIndexedKnowledgeItemRepository_FindByIDInIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDInIndex'
type MockIIndexedKnowledgeItemRepository_FindByIDInIndex_Call struct {
	*mock.Call
}

// FindByIDInIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - indexID string
//   - id string
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) FindByIDInIndex(ctx any, knowledgeID any, indexID any, id any) *MockIIndexedKnowledgeItemRepository_FindByIDInIndex_Call {
	return &MockIIndexedKnowledgeItemRepository_FindByIDInIndex_Call{Call: _e.mock.On("FindByIDInIndex", ctx, knowledgeID, indexID, id)}
}

func (_c *MockIIndexedKnowledgeItemRepository_FindByIDInIndex_Call) Run(run func(ctx context.Context, knowledgeID string, indexID string, id string)) *MockIIndexedKnowledgeItemRepository_FindByIDInIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_FindByIDInIndex_Call) Return(indexedKnowledgeItem *model.IndexedKnowledgeItem, err error) *MockIIndexedKnowledgeItemRepository_FindByIDInIndex_Call {
	_c.Call.Return(indexedKnowledgeItem, err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_FindByIDInIndex_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, indexID string, id string) (*model.IndexedKnowledgeItem, error)) *MockIIndexedKnowledgeItemRepository_FindByIDInIndex_Call {
	_c.Call.Return(run)
	return _c
}

// FindToCreateInIndex provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) FindToCreateInIndex(ctx context.Context, knowledgeID string, indexID string) ([]model.KnowledgeItem, error) {
	ret := _mock.Called(ctx, knowledgeID, indexID)

	if len(ret) == 0 {
		panic("no return value specified for FindToCreateInIndex")
	}

	var r0 []model.KnowledgeItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]model.KnowledgeItem, error)); ok {
		return returnFunc(ctx, knowledgeID, indexID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []model.KnowledgeItem); ok {
		r0 = returnFunc(ctx, knowledgeID, indexID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.KnowledgeItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, knowledgeID, indexID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIIndexedKnowledgeItemRepository_FindToCreateInIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindToCreateInIndex'
type MockIIndexedKnowledgeItemRepository_FindToCreateInIndex_Call struct {
	*mock.Call
}

// FindToCreateInIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - indexID string
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) FindToCreateInIndex(ctx any, knowledgeID any, indexID any) *MockIIndexedKnowledgeItemRepository_FindToCreateInIndex_Call {
	return &MockIIndexedKnowledgeItemRepository_FindToCreateInIndex_Call{Call: _e.mock.On("FindToCreateInIndex", ctx, knowledgeID, indexID)}
}

func (_c *MockIIndexedKnowledgeItemRepository_FindToCreateInIndex_Call) Run(run func(ctx context.Context, knowledgeID string, indexID string)) *MockIIndexedKnowledgeItemRepository_FindToCreateInIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_FindToCreateInIndex_Call) Return(knowledgeItems []model.KnowledgeItem, err error) *MockIIndexedKnowledgeItemRepository_FindToCreateInIndex_Call {
	_c.Call.Return(knowledgeItems, err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_FindToCreateInIndex_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, indexID string) ([]model.KnowledgeItem, error)) *MockIIndexedKnowledgeItemRepository_FindToCreateInIndex_Call {
	_c.Call.Return(run)
	return _c
}

// FindToDeleteInIndex provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) FindToDeleteInIndex(ctx context.Context, knowledgeID string, indexID string) ([]model.IndexedKnowledgeItem, error) {
	ret := _mock.Called(ctx, knowledgeID, indexID)

	if len(ret) == 0 {
		panic("no return value specified for FindToDeleteInIndex")
	}

	var r0 []model.IndexedKnowledgeItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]model.IndexedKnowledgeItem, error)); ok {
		return returnFunc(ctx, knowledgeID, indexID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []model.IndexedKnowledgeItem); ok {
		r0 = returnFunc(ctx, knowledgeID, indexID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.IndexedKnowledgeItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, knowledgeID, indexID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIIndexedKnowledgeItemRepository_FindToDeleteInIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindToDeleteInIndex'
type MockIIndexedKnowledgeItemRepository_FindToDeleteInIndex_Call struct {
	*mock.Call
}

// FindToDeleteInIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - indexID string
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) FindToDeleteInIndex(ctx any, knowledgeID any, indexID any) *MockIIndexedKnowledgeItemRepository_FindToDeleteInIndex_Call {
	return &MockIIndexedKnowledgeItemRepository_FindToDeleteInIndex_Call{Call: _e.mock.On("FindToDeleteInIndex", ctx, knowledgeID, indexID)}
}

func (_c *MockIIndexedKnowledgeItemRepository_FindToDeleteInIndex_Call) Run(run func(ctx context.Context, knowledgeID string, indexID string)) *MockIIndexedKnowledgeItemRepository_FindToDeleteInIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_FindToDeleteInIndex_Call) Return(indexedKnowledgeItems []model.IndexedKnowledgeItem, err error) *MockIIndexedKnowledgeItemRepository_FindToDeleteInIndex_Call {
	_c.Call.Return(indexedKnowledgeItems, err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_FindToDeleteInIndex_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, indexID string) ([]model.IndexedKnowledgeItem, error)) *MockIIndexedKnowledgeItemRepository_FindToDeleteInIndex_Call {
	_c.Call.Return(run)
	return _c
}

// FindToUpdateInIndex provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) FindToUpdateInIndex(ctx context.Context, knowledgeID string, indexID string) ([]model.IndexedKnowledgeItem, error) {
	ret := _mock.Called(ctx, knowledgeID, indexID)

	if len(ret) == 0 {
		panic("no return value specified for FindToUpdateInIndex")
	}

	var r0 []model.IndexedKnowledgeItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]model.IndexedKnowledgeItem, error)); ok {
		return returnFunc(ctx, knowledgeID, indexID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []model.IndexedKnowledgeItem); ok {
		r0 = returnFunc(ctx, knowledgeID, indexID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.IndexedKnowledgeItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, knowledgeID, indexID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIIndexedKnowledgeItemRepository_FindToUpdateInIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindToUpdateInIndex'
type MockIIndexedKnowledgeItemRepository_FindToUpdateInIndex_Call struct {
	*mock.Call
}

// FindToUpdateInIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - indexID string
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) FindToUpdateInIndex(ctx any, knowledgeID any, indexID any) *MockIIndexedKnowledgeItemRepository_FindToUpdateInIndex_Call {
	return &MockIIndexedKnowledgeItemRepository_FindToUpdateInIndex_Call{Call: _e.mock.On("FindToUpdateInIndex", ctx, knowledgeID, indexID)}
}

func (_c *MockIIndexedKnowledgeItemRepository_FindToUpdateInIndex_Call) Run(run func(ctx context.Context, knowledgeID string, indexID string)) *MockIIndexedKnowledgeItemRepository_FindToUpdateInIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_FindToUpdateInIndex_Call) Return(indexedKnowledgeItems []model.IndexedKnowledgeItem, err error) *MockIIndexedKnowledgeItemRepository_FindToUpdateInIndex_Call {
	_c.Call.Return(indexedKnowledgeItems, err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_FindToUpdateInIndex_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, indexID string) ([]model.IndexedKnowledgeItem, error)) *MockIIndexedKnowledgeItemRepository_FindToUpdateInIndex_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInIndex provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) UpdateInIndex(ctx context.Context, knowledgeID string, indexID string, id string, item *model.IndexedKnowledgeItem) error {
	ret := _mock.Called(ctx, knowledgeID, indexID, id, item)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInIndex")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *model.IndexedKnowledgeItem) error); ok {
		r0 = returnFunc(ctx, knowledgeID, indexID, id, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIIndexedKnowledgeItemRepository_UpdateInIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInIndex'
type MockIIndexedKnowledgeItemRepository_UpdateInIndex_Call struct {
	*mock.Call
}

// UpdateInIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - indexID string
//   - id string
//   - item *model.IndexedKnowledgeItem
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) UpdateInIndex(ctx any, knowledgeID any, indexID any, id any, item any) *MockIIndexedKnowledgeItemRepository_UpdateInIndex_Call {
	return &MockIIndexedKnowledgeItemRepository_UpdateInIndex_Call{Call: _e.mock.On("UpdateInIndex", ctx, knowledgeID, indexID, id, item)}
}

func (_c *MockIIndexedKnowledgeItemRepository_UpdateInIndex_Call) Run(run func(ctx context.Context, knowledgeID string, indexID string, id string, item *model.IndexedKnowledgeItem)) *MockIIndexedKnowledgeItemRepository_UpdateInIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *model.IndexedKnowledgeItem
		if args[4] != nil {
			arg4 = args[4].(*model.IndexedKnowledgeItem)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_UpdateInIndex_Call) Return(err error) *MockIIndexedKnowledgeItemRepository_UpdateInIndex_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_UpdateInIndex_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, indexID string, id string, item *model.IndexedKnowledgeItem) error) *MockIIndexedKnowledgeItemRepository_UpdateInIndex_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusesByIDsInIndex provides a mock function for the type MockIIndexedKnowledgeItemRepository
func (_mock *MockIIndexedKnowledgeItemRepository) UpdateStatusesByIDsInIndex(ctx context.Context, knowledgeID string, indexID string, ids []string, status model.IndexStatus) error {
	ret := _mock.Called(ctx, knowledgeID, indexID, ids, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusesByIDsInIndex")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string, model.IndexStatus) error); ok {
		r0 = returnFunc(ctx, knowledgeID, indexID, ids, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIIndexedKnowledgeItemRepository_UpdateStatusesByIDsInIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusesByIDsInIndex'
type MockIIndexedKnowledgeItemRepository_UpdateStatusesByIDsInIndex_Call struct {
	*mock.Call
}

// UpdateStatusesByIDsInIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - indexID string
//   - ids []string
//   - status model.IndexStatus
func (_e *MockIIndexedKnowledgeItemRepository_Expecter) UpdateStatusesByIDsInIndex(ctx any, knowledgeID any, indexID any, ids any, status any) *MockIIndexedKnowledgeItemRepository_UpdateStatusesByIDsInIndex_Call {
	return &MockIIndexedKnowledgeItemRepository_UpdateStatusesByIDsInIndex_Call{Call: _e.mock.On("UpdateStatusesByIDsInIndex", ctx, knowledgeID, indexID, ids, status)}
}

func (_c *MockIIndexedKnowledgeItemRepository_UpdateStatusesByIDsInIndex_Call) Run(run func(ctx context.Context, knowledgeID string, indexID string, ids []string, status model.IndexStatus)) *MockIIndexedKnowledgeItemRepository_UpdateStatusesByIDsInIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		var arg4 model.IndexStatus
		if args[4] != nil {
			arg4 = args[4].(model.IndexStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_UpdateStatusesByIDsInIndex_Call) Return(err error) *MockIIndexedKnowledgeItemRepository_UpdateStatusesByIDsInIndex_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIIndexedKnowledgeItemRepository_UpdateStatusesByIDsInIndex_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, indexID string, ids []string, status model.IndexStatus) error) *MockIIndexedKnowledgeItemRepository_UpdateStatusesByIDsInIndex_Call {
	_c.Call.Return(run)
	return _c
}
