// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIKnowledgeIndexRepository creates a new instance of MockIKnowledgeIndexRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIKnowledgeIndexRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIKnowledgeIndexRepository {
	mock := &MockIKnowledgeIndexRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIKnowledgeIndexRepository is an autogenerated mock type for the IKnowledgeIndexRepository type
type MockIKnowledgeIndexRepository struct {
	mock.Mock
}

type MockIKnowledgeIndexRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIKnowledgeIndexRepository) EXPECT() *MockIKnowledgeIndexRepository_Expecter {
	return &MockIKnowledgeIndexRepository_Expecter{mock: &_m.Mock}
}

// CreateInKnowledge provides a mock function for the type MockIKnowledgeIndexRepository
func (_mock *MockIKnowledgeIndexRepository) CreateInKnowledge(ctx context.Context, knowledgeID string, index *model.KnowledgeIndex) error {
	ret := _mock.Called(ctx, knowledgeID, index)

	if len(ret) == 0 {
		panic("no return value specified for CreateInKnowledge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.KnowledgeIndex) error); ok {
		r0 = returnFunc(ctx, knowledgeID, index)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIKnowledgeIndexRepository_CreateInKnowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInKnowledge'
type MockIKnowledgeIndexRepository_CreateInKnowledge_Call struct {
	*mock.Call
}

// CreateInKnowledge is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - index *model.KnowledgeIndex
func (_e *MockIKnowledgeIndexRepository_Expecter) CreateInKnowledge(ctx any, knowledgeID any, index any) *MockIKnowledgeIndexRepository_CreateInKnowledge_Call {
	return &MockIKnowledgeIndexRepository_CreateInKnowledge_Call{Call: _e.mock.On("CreateInKnowledge", ctx, knowledgeID, index)}
}

func (_c *MockIKnowledgeIndexRepository_CreateInKnowledge_Call) Run(run func(ctx context.Context, knowledgeID string, index *model.KnowledgeIndex)) *MockIKnowledgeIndexRepository_CreateInKnowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.KnowledgeIndex
		if args[2] != nil {
			arg2 = args[2].(*model.KnowledgeIndex)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIKnowledgeIndexRepository_CreateInKnowledge_Call) Return(err error) *MockIKnowledgeIndexRepository_CreateInKnowledge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIKnowledgeIndexRepository_CreateInKnowledge_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, index *model.KnowledgeIndex) error) *MockIKnowledgeIndexRepository_CreateInKnowledge_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInKnowledge provides a mock function for the type MockIKnowledgeIndexRepository
func (_mock *MockIKnowledgeIndexRepository) DeleteInKnowledge(ctx context.Context, knowledgeID string, id string) error {
	ret := _mock.Called(ctx, knowledgeID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInKnowledge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, knowledgeID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIKnowledgeIndexRepository_DeleteInKnowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInKnowledge'
type MockIKnowledgeIndexRepository_DeleteInKnowledge_Call struct {
	*mock.Call
}

// DeleteInKnowledge is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - id string
func (_e *MockIKnowledgeIndexRepository_Expecter) DeleteInKnowledge(ctx any, knowledgeID any, id any) *MockIKnowledgeIndexRepository_DeleteInKnowledge_Call {
	return &MockIKnowledgeIndexRepository_DeleteInKnowledge_Call{Call: _e.mock.On("DeleteInKnowledge", ctx, knowledgeID, id)}
}

func (_c *MockIKnowledgeIndexRepository_DeleteInKnowledge_Call) Run(run func(ctx context.Context, knowledgeID string, id string)) *MockIKnowledgeIndexRepository_DeleteInKnowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIKnowledgeIndexRepository_DeleteInKnowledge_Call) Return(err error) *MockIKnowledgeIndexRepository_DeleteInKnowledge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIKnowledgeIndexRepository_DeleteInKnowledge_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, id string) error) *MockIKnowledgeIndexRepository_DeleteInKnowledge_Call {
	_c.Call.Return(run)
	return _c
}

// FilterInKnowledge provides a mock function for the type MockIKnowledgeIndexRepository
func (_mock *MockIKnowledgeIndexRepository) FilterInKnowledge(ctx context.Context, knowledgeID string, filter1 *filter.Options[model.KnowledgeIndex]) (*page.Paginated[model.KnowledgeIndex], error) {
	ret := _mock.Called(ctx, knowledgeID, filter1)

	if len(ret) == 0 {
		panic("no return value specified for FilterInKnowledge")
	}

	var r0 *page.Paginated[model.KnowledgeIndex]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *filter.Options[model.KnowledgeIndex]) (*page.Paginated[model.KnowledgeIndex], error)); ok {
		return returnFunc(ctx, knowledgeID, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *filter.Options[model.KnowledgeIndex]) *page.Paginated[model.KnowledgeIndex]); ok {
		r0 = returnFunc(ctx, knowledgeID, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.KnowledgeIndex])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *filter.Options[model.KnowledgeIndex]) error); ok {
		r1 = returnFunc(ctx, knowledgeID, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIKnowledgeIndexRepository_FilterInKnowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterInKnowledge'
type MockIKnowledgeIndexRepository_FilterInKnowledge_Call struct {
	*mock.Call
}

// FilterInKnowledge is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - filter1 *filter.Options[model.KnowledgeIndex]
func (_e *MockIKnowledgeIndexRepository_Expecter) FilterInKnowledge(ctx any, knowledgeID any, filter1 any) *MockIKnowledgeIndexRepository_FilterInKnowledge_Call {
	return &MockIKnowledgeIndexRepository_FilterInKnowledge_Call{Call: _e.mock.On("FilterInKnowledge", ctx, knowledgeID, filter1)}
}

func (_c *MockIKnowledgeIndexRepository_FilterInKnowledge_Call) Run(run func(ctx context.Context, knowledgeID string, filter1 *filter.Options[model.KnowledgeIndex])) *MockIKnowledgeIndexRepository_FilterInKnowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *filter.Options[model.KnowledgeIndex]
		if args[2] != nil {
			arg2 = args[2].(*filter.Options[model.KnowledgeIndex])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIKnowledgeIndexRepository_FilterInKnowledge_Call) Return(paginated *page.Paginated[model.KnowledgeIndex], err error) *MockIKnowledgeIndexRepository_FilterInKnowledge_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIKnowledgeIndexRepository_FilterInKnowledge_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, filter1 *filter.Options[model.KnowledgeIndex]) (*page.Paginated[model.KnowledgeIndex], error)) *MockIKnowledgeIndexRepository_FilterInKnowledge_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDInKnowledge provides a mock function for the type MockIKnowledgeIndexRepository
func (_mock *MockIKnowledgeIndexRepository) FindByIDInKnowledge(ctx context.Context, knowledgeID string, id string) (*model.KnowledgeIndex, error) {
	ret := _mock.Called(ctx, knowledgeID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDInKnowledge")
	}

	var r0 *model.KnowledgeIndex
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.KnowledgeIndex, error)); ok {
		return returnFunc(ctx, knowledgeID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.KnowledgeIndex); ok {
		r0 = returnFunc(ctx, knowledgeID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KnowledgeIndex)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, knowledgeID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIKnowledgeIndexRepository_FindByIDInKnowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDInKnowledge'
type MockIKnowledgeIndexRepository_FindByIDInKnowledge_Call struct {
	*mock.Call
}

// FindByIDInKnowledge is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - id string
func (_e *MockIKnowledgeIndexRepository_Expecter) FindByIDInKnowledge(ctx any, knowledgeID any, id any) *MockIKnowledgeIndexRepository_FindByIDInKnowledge_Call {
	return &MockIKnowledgeIndexRepository_FindByIDInKnowledge_Call{Call: _e.mock.On("FindByIDInKnowledge", ctx, knowledgeID, id)}
}

func (_c *MockIKnowledgeIndexRepository_FindByIDInKnowledge_Call) Run(run func(ctx context.Context, knowledgeID string, id string)) *MockIKnowledgeIndexRepository_FindByIDInKnowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIKnowledgeIndexRepository_FindByIDInKnowledge_Call) Return(knowledgeIndex *model.KnowledgeIndex, err error) *MockIKnowledgeIndexRepository_FindByIDInKnowledge_Call {
	_c.Call.Return(knowledgeIndex, err)
	return _c
}

func (_c *MockIKnowledgeIndexRepository_FindByIDInKnowledge_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, id string) (*model.KnowledgeIndex, error)) *MockIKnowledgeIndexRepository_FindByIDInKnowledge_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNameInKnowledge provides a mock function for the type MockIKnowledgeIndexRepository
func (_mock *MockIKnowledgeIndexRepository) UpdateNameInKnowledge(ctx context.Context, knowledgeID string, id string, name string) error {
	ret := _mock.Called(ctx, knowledgeID, id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNameInKnowledge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, knowledgeID, id, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIKnowledgeIndexRepository_UpdateNameInKnowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNameInKnowledge'
type MockIKnowledgeIndexRepository_UpdateNameInKnowledge_Call struct {
	*mock.Call
}

// UpdateNameInKnowledge is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - id string
//   - name string
func (_e *MockIKnowledgeIndexRepository_Expecter) UpdateNameInKnowledge(ctx any, knowledgeID any, id any, name any) *MockIKnowledgeIndexRepository_UpdateNameInKnowledge_Call {
	return &MockIKnowledgeIndexRepository_UpdateNameInKnowledge_Call{Call: _e.mock.On("UpdateNameInKnowledge", ctx, knowledgeID, id, name)}
}

func (_c *MockIKnowledgeIndexRepository_UpdateNameInKnowledge_Call) Run(run func(ctx context.Context, knowledgeID string, id string, name string)) *MockIKnowledgeIndexRepository_UpdateNameInKnowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIKnowledgeIndexRepository_UpdateNameInKnowledge_Call) Return(err error) *MockIKnowledgeIndexRepository_UpdateNameInKnowledge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIKnowledgeIndexRepository_UpdateNameInKnowledge_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, id string, name string) error) *MockIKnowledgeIndexRepository_UpdateNameInKnowledge_Call {
	_c.Call.Return(run)
	return _c
}
