// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIKnowledgeItemRepository creates a new instance of MockIKnowledgeItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIKnowledgeItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIKnowledgeItemRepository {
	mock := &MockIKnowledgeItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIKnowledgeItemRepository is an autogenerated mock type for the IKnowledgeItemRepository type
type MockIKnowledgeItemRepository struct {
	mock.Mock
}

type MockIKnowledgeItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIKnowledgeItemRepository) EXPECT() *MockIKnowledgeItemRepository_Expecter {
	return &MockIKnowledgeItemRepository_Expecter{mock: &_m.Mock}
}

// CreateInKnowledge provides a mock function for the type MockIKnowledgeItemRepository
func (_mock *MockIKnowledgeItemRepository) CreateInKnowledge(ctx context.Context, knowledgeID string, item *model.KnowledgeItem) error {
	ret := _mock.Called(ctx, knowledgeID, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateInKnowledge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.KnowledgeItem) error); ok {
		r0 = returnFunc(ctx, knowledgeID, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIKnowledgeItemRepository_CreateInKnowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInKnowledge'
type MockIKnowledgeItemRepository_CreateInKnowledge_Call struct {
	*mock.Call
}

// CreateInKnowledge is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - item *model.KnowledgeItem
func (_e *MockIKnowledgeItemRepository_Expecter) CreateInKnowledge(ctx any, knowledgeID any, item any) *MockIKnowledgeItemRepository_CreateInKnowledge_Call {
	return &MockIKnowledgeItemRepository_CreateInKnowledge_Call{Call: _e.mock.On("CreateInKnowledge", ctx, knowledgeID, item)}
}

func (_c *MockIKnowledgeItemRepository_CreateInKnowledge_Call) Run(run func(ctx context.Context, knowledgeID string, item *model.KnowledgeItem)) *MockIKnowledgeItemRepository_CreateInKnowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.KnowledgeItem
		if args[2] != nil {
			arg2 = args[2].(*model.KnowledgeItem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIKnowledgeItemRepository_CreateInKnowledge_Call) Return(err error) *MockIKnowledgeItemRepository_CreateInKnowledge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIKnowledgeItemRepository_CreateInKnowledge_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, item *model.KnowledgeItem) error) *MockIKnowledgeItemRepository_CreateInKnowledge_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInKnowledge provides a mock function for the type MockIKnowledgeItemRepository
func (_mock *MockIKnowledgeItemRepository) DeleteInKnowledge(ctx context.Context, knowledgeID string, id string) error {
	ret := _mock.Called(ctx, knowledgeID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInKnowledge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, knowledgeID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIKnowledgeItemRepository_DeleteInKnowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInKnowledge'
type MockIKnowledgeItemRepository_DeleteInKnowledge_Call struct {
	*mock.Call
}

// DeleteInKnowledge is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - id string
func (_e *MockIKnowledgeItemRepository_Expecter) DeleteInKnowledge(ctx any, knowledgeID any, id any) *MockIKnowledgeItemRepository_DeleteInKnowledge_Call {
	return &MockIKnowledgeItemRepository_DeleteInKnowledge_Call{Call: _e.mock.On("DeleteInKnowledge", ctx, knowledgeID, id)}
}

func (_c *MockIKnowledgeItemRepository_DeleteInKnowledge_Call) Run(run func(ctx context.Context, knowledgeID string, id string)) *MockIKnowledgeItemRepository_DeleteInKnowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIKnowledgeItemRepository_DeleteInKnowledge_Call) Return(err error) *MockIKnowledgeItemRepository_DeleteInKnowledge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIKnowledgeItemRepository_DeleteInKnowledge_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, id string) error) *MockIKnowledgeItemRepository_DeleteInKnowledge_Call {
	_c.Call.Return(run)
	return _c
}

// FilterInKnowledge provides a mock function for the type MockIKnowledgeItemRepository
func (_mock *MockIKnowledgeItemRepository) FilterInKnowledge(ctx context.Context, knowledgeID string, filter1 *filter.Options[model.KnowledgeItem]) (*page.Paginated[model.KnowledgeItem], error) {
	ret := _mock.Called(ctx, knowledgeID, filter1)

	if len(ret) == 0 {
		panic("no return value specified for FilterInKnowledge")
	}

	var r0 *page.Paginated[model.KnowledgeItem]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *filter.Options[model.KnowledgeItem]) (*page.Paginated[model.KnowledgeItem], error)); ok {
		return returnFunc(ctx, knowledgeID, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *filter.Options[model.KnowledgeItem]) *page.Paginated[model.KnowledgeItem]); ok {
		r0 = returnFunc(ctx, knowledgeID, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.KnowledgeItem])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *filter.Options[model.KnowledgeItem]) error); ok {
		r1 = returnFunc(ctx, knowledgeID, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIKnowledgeItemRepository_FilterInKnowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterInKnowledge'
type MockIKnowledgeItemRepository_FilterInKnowledge_Call struct {
	*mock.Call
}

// FilterInKnowledge is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - filter1 *filter.Options[model.KnowledgeItem]
func (_e *MockIKnowledgeItemRepository_Expecter) FilterInKnowledge(ctx any, knowledgeID any, filter1 any) *MockIKnowledgeItemRepository_FilterInKnowledge_Call {
	return &MockIKnowledgeItemRepository_FilterInKnowledge_Call{Call: _e.mock.On("FilterInKnowledge", ctx, knowledgeID, filter1)}
}

func (_c *MockIKnowledgeItemRepository_FilterInKnowledge_Call) Run(run func(ctx context.Context, knowledgeID string, filter1 *filter.Options[model.KnowledgeItem])) *MockIKnowledgeItemRepository_FilterInKnowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *filter.Options[model.KnowledgeItem]
		if args[2] != nil {
			arg2 = args[2].(*filter.Options[model.KnowledgeItem])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIKnowledgeItemRepository_FilterInKnowledge_Call) Return(paginated *page.Paginated[model.KnowledgeItem], err error) *MockIKnowledgeItemRepository_FilterInKnowledge_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIKnowledgeItemRepository_FilterInKnowledge_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, filter1 *filter.Options[model.KnowledgeItem]) (*page.Paginated[model.KnowledgeItem], error)) *MockIKnowledgeItemRepository_FilterInKnowledge_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDInKnowledge provides a mock function for the type MockIKnowledgeItemRepository
func (_mock *MockIKnowledgeItemRepository) FindByIDInKnowledge(ctx context.Context, knowledgeID string, id string) (*model.KnowledgeItem, error) {
	ret := _mock.Called(ctx, knowledgeID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDInKnowledge")
	}

	var r0 *model.KnowledgeItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.KnowledgeItem, error)); ok {
		return returnFunc(ctx, knowledgeID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.KnowledgeItem); ok {
		r0 = returnFunc(ctx, knowledgeID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KnowledgeItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, knowledgeID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIKnowledgeItemRepository_FindByIDInKnowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDInKnowledge'
type MockIKnowledgeItemRepository_FindByIDInKnowledge_Call struct {
	*mock.Call
}

// FindByIDInKnowledge is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - id string
func (_e *MockIKnowledgeItemRepository_Expecter) FindByIDInKnowledge(ctx any, knowledgeID any, id any) *MockIKnowledgeItemRepository_FindByIDInKnowledge_Call {
	return &MockIKnowledgeItemRepository_FindByIDInKnowledge_Call{Call: _e.mock.On("FindByIDInKnowledge", ctx, knowledgeID, id)}
}

func (_c *MockIKnowledgeItemRepository_FindByIDInKnowledge_Call) Run(run func(ctx context.Context, knowledgeID string, id string)) *MockIKnowledgeItemRepository_FindByIDInKnowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIKnowledgeItemRepository_FindByIDInKnowledge_Call) Return(knowledgeItem *model.KnowledgeItem, err error) *MockIKnowledgeItemRepository_FindByIDInKnowledge_Call {
	_c.Call.Return(knowledgeItem, err)
	return _c
}

func (_c *MockIKnowledgeItemRepository_FindByIDInKnowledge_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, id string) (*model.KnowledgeItem, error)) *MockIKnowledgeItemRepository_FindByIDInKnowledge_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInKnowledge provides a mock function for the type MockIKnowledgeItemRepository
func (_mock *MockIKnowledgeItemRepository) UpdateInKnowledge(ctx context.Context, knowledgeID string, id string, item *model.KnowledgeItem) error {
	ret := _mock.Called(ctx, knowledgeID, id, item)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInKnowledge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *model.KnowledgeItem) error); ok {
		r0 = returnFunc(ctx, knowledgeID, id, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIKnowledgeItemRepository_UpdateInKnowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInKnowledge'
type MockIKnowledgeItemRepository_UpdateInKnowledge_Call struct {
	*mock.Call
}

// UpdateInKnowledge is a helper method to define mock.On call
//   - ctx context.Context
//   - knowledgeID string
//   - id string
//   - item *model.KnowledgeItem
func (_e *MockIKnowledgeItemRepository_Expecter) UpdateInKnowledge(ctx any, knowledgeID any, id any, item any) *MockIKnowledgeItemRepository_UpdateInKnowledge_Call {
	return &MockIKnowledgeItemRepository_UpdateInKnowledge_Call{Call: _e.mock.On("UpdateInKnowledge", ctx, knowledgeID, id, item)}
}

func (_c *MockIKnowledgeItemRepository_UpdateInKnowledge_Call) Run(run func(ctx context.Context, knowledgeID string, id string, item *model.KnowledgeItem)) *MockIKnowledgeItemRepository_UpdateInKnowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *model.KnowledgeItem
		if args[3] != nil {
			arg3 = args[3].(*model.KnowledgeItem)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIKnowledgeItemRepository_UpdateInKnowledge_Call) Return(err error) *MockIKnowledgeItemRepository_UpdateInKnowledge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIKnowledgeItemRepository_UpdateInKnowledge_Call) RunAndReturn(run func(ctx context.Context, knowledgeID string, id string, item *model.KnowledgeItem) error) *MockIKnowledgeItemRepository_UpdateInKnowledge_Call {
	_c.Call.Return(run)
	return _c
}
