// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIMemberRepository creates a new instance of MockIMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMemberRepository {
	mock := &MockIMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIMemberRepository is an autogenerated mock type for the IMemberRepository type
type MockIMemberRepository struct {
	mock.Mock
}

type MockIMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMemberRepository) EXPECT() *MockIMemberRepository_Expecter {
	return &MockIMemberRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIMemberRepository
func (_mock *MockIMemberRepository) Create(ctx context.Context, model1 *model.Member) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Member) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMemberRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIMemberRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.Member
func (_e *MockIMemberRepository_Expecter) Create(ctx any, model1 any) *MockIMemberRepository_Create_Call {
	return &MockIMemberRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockIMemberRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.Member)) *MockIMemberRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Member
		if args[1] != nil {
			arg1 = args[1].(*model.Member)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMemberRepository_Create_Call) Return(err error) *MockIMemberRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMemberRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.Member) error) *MockIMemberRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockIMemberRepository
func (_mock *MockIMemberRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMemberRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIMemberRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIMemberRepository_Expecter) DeleteByID(ctx any, id any) *MockIMemberRepository_DeleteByID_Call {
	return &MockIMemberRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockIMemberRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockIMemberRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMemberRepository_DeleteByID_Call) Return(err error) *MockIMemberRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMemberRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIMemberRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockIMemberRepository
func (_mock *MockIMemberRepository) Filter(ctx context.Context, filter1 *filter.Options[model.Member]) (*page.Paginated[model.Member], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.Member]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.Member]) (*page.Paginated[model.Member], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.Member]) *page.Paginated[model.Member]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.Member])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.Member]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMemberRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockIMemberRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.Member]
func (_e *MockIMemberRepository_Expecter) Filter(ctx any, filter1 any) *MockIMemberRepository_Filter_Call {
	return &MockIMemberRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockIMemberRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.Member])) *MockIMemberRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.Member]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.Member])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMemberRepository_Filter_Call) Return(paginated *page.Paginated[model.Member], err error) *MockIMemberRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIMemberRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.Member]) (*page.Paginated[model.Member], error)) *MockIMemberRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FilterWithUser provides a mock function for the type MockIMemberRepository
func (_mock *MockIMemberRepository) FilterWithUser(ctx context.Context, opts *filter.Options[model.Member]) (*page.Paginated[model.Member], error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for FilterWithUser")
	}

	var r0 *page.Paginated[model.Member]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.Member]) (*page.Paginated[model.Member], error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.Member]) *page.Paginated[model.Member]); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.Member])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.Member]) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMemberRepository_FilterWithUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterWithUser'
type MockIMemberRepository_FilterWithUser_Call struct {
	*mock.Call
}

// FilterWithUser is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *filter.Options[model.Member]
func (_e *MockIMemberRepository_Expecter) FilterWithUser(ctx any, opts any) *MockIMemberRepository_FilterWithUser_Call {
	return &MockIMemberRepository_FilterWithUser_Call{Call: _e.mock.On("FilterWithUser", ctx, opts)}
}

func (_c *MockIMemberRepository_FilterWithUser_Call) Run(run func(ctx context.Context, opts *filter.Options[model.Member])) *MockIMemberRepository_FilterWithUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.Member]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.Member])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMemberRepository_FilterWithUser_Call) Return(paginated *page.Paginated[model.Member], err error) *MockIMemberRepository_FilterWithUser_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIMemberRepository_FilterWithUser_Call) RunAndReturn(run func(ctx context.Context, opts *filter.Options[model.Member]) (*page.Paginated[model.Member], error)) *MockIMemberRepository_FilterWithUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIMemberRepository
func (_mock *MockIMemberRepository) FindByID(ctx context.Context, id string) (*model.Member, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Member, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Member); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMemberRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIMemberRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIMemberRepository_Expecter) FindByID(ctx any, id any) *MockIMemberRepository_FindByID_Call {
	return &MockIMemberRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIMemberRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockIMemberRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMemberRepository_FindByID_Call) Return(member *model.Member, err error) *MockIMemberRepository_FindByID_Call {
	_c.Call.Return(member, err)
	return _c
}

func (_c *MockIMemberRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Member, error)) *MockIMemberRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserAndTenant provides a mock function for the type MockIMemberRepository
func (_mock *MockIMemberRepository) FindByUserAndTenant(ctx context.Context, userID string, tenantID string) (*model.Member, error) {
	ret := _mock.Called(ctx, userID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndTenant")
	}

	var r0 *model.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Member, error)); ok {
		return returnFunc(ctx, userID, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Member); ok {
		r0 = returnFunc(ctx, userID, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMemberRepository_FindByUserAndTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserAndTenant'
type MockIMemberRepository_FindByUserAndTenant_Call struct {
	*mock.Call
}

// FindByUserAndTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tenantID string
func (_e *MockIMemberRepository_Expecter) FindByUserAndTenant(ctx any, userID any, tenantID any) *MockIMemberRepository_FindByUserAndTenant_Call {
	return &MockIMemberRepository_FindByUserAndTenant_Call{Call: _e.mock.On("FindByUserAndTenant", ctx, userID, tenantID)}
}

func (_c *MockIMemberRepository_FindByUserAndTenant_Call) Run(run func(ctx context.Context, userID string, tenantID string)) *MockIMemberRepository_FindByUserAndTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIMemberRepository_FindByUserAndTenant_Call) Return(member *model.Member, err error) *MockIMemberRepository_FindByUserAndTenant_Call {
	_c.Call.Return(member, err)
	return _c
}

func (_c *MockIMemberRepository_FindByUserAndTenant_Call) RunAndReturn(run func(ctx context.Context, userID string, tenantID string) (*model.Member, error)) *MockIMemberRepository_FindByUserAndTenant_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockIMemberRepository
func (_mock *MockIMemberRepository) UpdateByID(ctx context.Context, id string, model1 *model.Member) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.Member) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMemberRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockIMemberRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.Member
func (_e *MockIMemberRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockIMemberRepository_UpdateByID_Call {
	return &MockIMemberRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockIMemberRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.Member)) *MockIMemberRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.Member
		if args[2] != nil {
			arg2 = args[2].(*model.Member)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIMemberRepository_UpdateByID_Call) Return(err error) *MockIMemberRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMemberRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.Member) error) *MockIMemberRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
