// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIMemoryRepository creates a new instance of MockIMemoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMemoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMemoryRepository {
	mock := &MockIMemoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIMemoryRepository is an autogenerated mock type for the IMemoryRepository type
type MockIMemoryRepository struct {
	mock.Mock
}

type MockIMemoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMemoryRepository) EXPECT() *MockIMemoryRepository_Expecter {
	return &MockIMemoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIMemoryRepository
func (_mock *MockIMemoryRepository) Create(ctx context.Context, model1 *model.Memory) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Memory) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMemoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIMemoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.Memory
func (_e *MockIMemoryRepository_Expecter) Create(ctx any, model1 any) *MockIMemoryRepository_Create_Call {
	return &MockIMemoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockIMemoryRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.Memory)) *MockIMemoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Memory
		if args[1] != nil {
			arg1 = args[1].(*model.Memory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMemoryRepository_Create_Call) Return(err error) *MockIMemoryRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMemoryRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.Memory) error) *MockIMemoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockIMemoryRepository
func (_mock *MockIMemoryRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMemoryRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIMemoryRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIMemoryRepository_Expecter) DeleteByID(ctx any, id any) *MockIMemoryRepository_DeleteByID_Call {
	return &MockIMemoryRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockIMemoryRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockIMemoryRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMemoryRepository_DeleteByID_Call) Return(err error) *MockIMemoryRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMemoryRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIMemoryRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockIMemoryRepository
func (_mock *MockIMemoryRepository) Filter(ctx context.Context, filter1 *filter.Options[model.Memory]) (*page.Paginated[model.Memory], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.Memory]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.Memory]) (*page.Paginated[model.Memory], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.Memory]) *page.Paginated[model.Memory]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.Memory])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.Memory]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMemoryRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockIMemoryRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.Memory]
func (_e *MockIMemoryRepository_Expecter) Filter(ctx any, filter1 any) *MockIMemoryRepository_Filter_Call {
	return &MockIMemoryRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockIMemoryRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.Memory])) *MockIMemoryRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.Memory]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.Memory])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMemoryRepository_Filter_Call) Return(paginated *page.Paginated[model.Memory], err error) *MockIMemoryRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIMemoryRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.Memory]) (*page.Paginated[model.Memory], error)) *MockIMemoryRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIMemoryRepository
func (_mock *MockIMemoryRepository) FindByID(ctx context.Context, id string) (*model.Memory, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Memory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Memory, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Memory); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Memory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMemoryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIMemoryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIMemoryRepository_Expecter) FindByID(ctx any, id any) *MockIMemoryRepository_FindByID_Call {
	return &MockIMemoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIMemoryRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockIMemoryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMemoryRepository_FindByID_Call) Return(memory *model.Memory, err error) *MockIMemoryRepository_FindByID_Call {
	_c.Call.Return(memory, err)
	return _c
}

func (_c *MockIMemoryRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Memory, error)) *MockIMemoryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// SetAsDefault provides a mock function for the type MockIMemoryRepository
func (_mock *MockIMemoryRepository) SetAsDefault(ctx context.Context, memoryType model.MemoryType, memoryID string) error {
	ret := _mock.Called(ctx, memoryType, memoryID)

	if len(ret) == 0 {
		panic("no return value specified for SetAsDefault")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.MemoryType, string) error); ok {
		r0 = returnFunc(ctx, memoryType, memoryID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMemoryRepository_SetAsDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAsDefault'
type MockIMemoryRepository_SetAsDefault_Call struct {
	*mock.Call
}

// SetAsDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - memoryType model.MemoryType
//   - memoryID string
func (_e *MockIMemoryRepository_Expecter) SetAsDefault(ctx any, memoryType any, memoryID any) *MockIMemoryRepository_SetAsDefault_Call {
	return &MockIMemoryRepository_SetAsDefault_Call{Call: _e.mock.On("SetAsDefault", ctx, memoryType, memoryID)}
}

func (_c *MockIMemoryRepository_SetAsDefault_Call) Run(run func(ctx context.Context, memoryType model.MemoryType, memoryID string)) *MockIMemoryRepository_SetAsDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.MemoryType
		if args[1] != nil {
			arg1 = args[1].(model.MemoryType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIMemoryRepository_SetAsDefault_Call) Return(err error) *MockIMemoryRepository_SetAsDefault_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMemoryRepository_SetAsDefault_Call) RunAndReturn(run func(ctx context.Context, memoryType model.MemoryType, memoryID string) error) *MockIMemoryRepository_SetAsDefault_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockIMemoryRepository
func (_mock *MockIMemoryRepository) UpdateByID(ctx context.Context, id string, model1 *model.Memory) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.Memory) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMemoryRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockIMemoryRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.Memory
func (_e *MockIMemoryRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockIMemoryRepository_UpdateByID_Call {
	return &MockIMemoryRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockIMemoryRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.Memory)) *MockIMemoryRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.Memory
		if args[2] != nil {
			arg2 = args[2].(*model.Memory)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIMemoryRepository_UpdateByID_Call) Return(err error) *MockIMemoryRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMemoryRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.Memory) error) *MockIMemoryRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
