// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/model"
)

// NewMockIRefreshTokenRepository creates a new instance of MockIRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRefreshTokenRepository {
	mock := &MockIRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRefreshTokenRepository is an autogenerated mock type for the IRefreshTokenRepository type
type MockIRefreshTokenRepository struct {
	mock.Mock
}

type MockIRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRefreshTokenRepository) EXPECT() *MockIRefreshTokenRepository_Expecter {
	return &MockIRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIRefreshTokenRepository
func (_mock *MockIRefreshTokenRepository) Create(ctx context.Context, token *model.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *model.RefreshToken
func (_e *MockIRefreshTokenRepository_Expecter) Create(ctx any, token any) *MockIRefreshTokenRepository_Create_Call {
	return &MockIRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockIRefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, token *model.RefreshToken)) *MockIRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*model.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRefreshTokenRepository_Create_Call) Return(err error) *MockIRefreshTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRefreshTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, token *model.RefreshToken) error) *MockIRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHash provides a mock function for the type MockIRefreshTokenRepository
func (_mock *MockIRefreshTokenRepository) FindByHash(ctx context.Context, hash string) (*model.RefreshToken, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for FindByHash")
	}

	var r0 *model.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.RefreshToken, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.RefreshToken); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRefreshTokenRepository_FindByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHash'
type MockIRefreshTokenRepository_FindByHash_Call struct {
	*mock.Call
}

// FindByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockIRefreshTokenRepository_Expecter) FindByHash(ctx any, hash any) *MockIRefreshTokenRepository_FindByHash_Call {
	return &MockIRefreshTokenRepository_FindByHash_Call{Call: _e.mock.On("FindByHash", ctx, hash)}
}

func (_c *MockIRefreshTokenRepository_FindByHash_Call) Run(run func(ctx context.Context, hash string)) *MockIRefreshTokenRepository_FindByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRefreshTokenRepository_FindByHash_Call) Return(refreshToken *model.RefreshToken, err error) *MockIRefreshTokenRepository_FindByHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockIRefreshTokenRepository_FindByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*model.RefreshToken, error)) *MockIRefreshTokenRepository_FindByHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByID provides a mock function for the type MockIRefreshTokenRepository
func (_mock *MockIRefreshTokenRepository) RevokeByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRefreshTokenRepository_RevokeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByID'
type MockIRefreshTokenRepository_RevokeByID_Call struct {
	*mock.Call
}

// RevokeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIRefreshTokenRepository_Expecter) RevokeByID(ctx any, id any) *MockIRefreshTokenRepository_RevokeByID_Call {
	return &MockIRefreshTokenRepository_RevokeByID_Call{Call: _e.mock.On("RevokeByID", ctx, id)}
}

func (_c *MockIRefreshTokenRepository_RevokeByID_Call) Run(run func(ctx context.Context, id string)) *MockIRefreshTokenRepository_RevokeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRefreshTokenRepository_RevokeByID_Call) Return(err error) *MockIRefreshTokenRepository_RevokeByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRefreshTokenRepository_RevokeByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIRefreshTokenRepository_RevokeByID_Call {
	_c.Call.Return(run)
	return _c
}
