// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockISessionRepository creates a new instance of MockISessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISessionRepository {
	mock := &MockISessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockISessionRepository is an autogenerated mock type for the ISessionRepository type
type MockISessionRepository struct {
	mock.Mock
}

type MockISessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISessionRepository) EXPECT() *MockISessionRepository_Expecter {
	return &MockISessionRepository_Expecter{mock: &_m.Mock}
}

// CheckUserAccess provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) CheckUserAccess(ctx context.Context, clientCode string, userID string, sessionID string) (bool, error) {
	ret := _mock.Called(ctx, clientCode, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserAccess")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, clientCode, userID, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, clientCode, userID, sessionID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, clientCode, userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionRepository_CheckUserAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserAccess'
type MockISessionRepository_CheckUserAccess_Call struct {
	*mock.Call
}

// CheckUserAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - clientCode string
//   - userID string
//   - sessionID string
func (_e *MockISessionRepository_Expecter) CheckUserAccess(ctx any, clientCode any, userID any, sessionID any) *MockISessionRepository_CheckUserAccess_Call {
	return &MockISessionRepository_CheckUserAccess_Call{Call: _e.mock.On("CheckUserAccess", ctx, clientCode, userID, sessionID)}
}

func (_c *MockISessionRepository_CheckUserAccess_Call) Run(run func(ctx context.Context, clientCode string, userID string, sessionID string)) *MockISessionRepository_CheckUserAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockISessionRepository_CheckUserAccess_Call) Return(b bool, err error) *MockISessionRepository_CheckUserAccess_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockISessionRepository_CheckUserAccess_Call) RunAndReturn(run func(ctx context.Context, clientCode string, userID string, sessionID string) (bool, error)) *MockISessionRepository_CheckUserAccess_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInClient provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) CreateInClient(ctx context.Context, clientCode string, session *model.Session) error {
	ret := _mock.Called(ctx, clientCode, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateInClient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.Session) error); ok {
		r0 = returnFunc(ctx, clientCode, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockISessionRepository_CreateInClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInClient'
type MockISessionRepository_CreateInClient_Call struct {
	*mock.Call
}

// CreateInClient is a helper method to define mock.On call
//   - ctx context.Context
//   - clientCode string
//   - session *model.Session
func (_e *MockISessionRepository_Expecter) CreateInClient(ctx any, clientCode any, session any) *MockISessionRepository_CreateInClient_Call {
	return &MockISessionRepository_CreateInClient_Call{Call: _e.mock.On("CreateInClient", ctx, clientCode, session)}
}

func (_c *MockISessionRepository_CreateInClient_Call) Run(run func(ctx context.Context, clientCode string, session *model.Session)) *MockISessionRepository_CreateInClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.Session
		if args[2] != nil {
			arg2 = args[2].(*model.Session)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockISessionRepository_CreateInClient_Call) Return(err error) *MockISessionRepository_CreateInClient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockISessionRepository_CreateInClient_Call) RunAndReturn(run func(ctx context.Context, clientCode string, session *model.Session) error) *MockISessionRepository_CreateInClient_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInClient provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) DeleteInClient(ctx context.Context, clientCode string, id string) error {
	ret := _mock.Called(ctx, clientCode, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInClient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, clientCode, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockISessionRepository_DeleteInClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInClient'
type MockISessionRepository_DeleteInClient_Call struct {
	*mock.Call
}

// DeleteInClient is a helper method to define mock.On call
//   - ctx context.Context
//   - clientCode string
//   - id string
func (_e *MockISessionRepository_Expecter) DeleteInClient(ctx any, clientCode any, id any) *MockISessionRepository_DeleteInClient_Call {
	return &MockISessionRepository_DeleteInClient_Call{Call: _e.mock.On("DeleteInClient", ctx, clientCode, id)}
}

func (_c *MockISessionRepository_DeleteInClient_Call) Run(run func(ctx context.Context, clientCode string, id string)) *MockISessionRepository_DeleteInClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockISessionRepository_DeleteInClient_Call) Return(err error) *MockISessionRepository_DeleteInClient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockISessionRepository_DeleteInClient_Call) RunAndReturn(run func(ctx context.Context, clientCode string, id string) error) *MockISessionRepository_DeleteInClient_Call {
	_c.Call.Return(run)
	return _c
}

// FilterInClient provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) FilterInClient(ctx context.Context, clientCode string, filter1 *filter.Options[model.Session]) (*page.Paginated[model.Session], error) {
	ret := _mock.Called(ctx, clientCode, filter1)

	if len(ret) == 0 {
		panic("no return value specified for FilterInClient")
	}

	var r0 *page.Paginated[model.Session]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *filter.Options[model.Session]) (*page.Paginated[model.Session], error)); ok {
		return returnFunc(ctx, clientCode, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *filter.Options[model.Session]) *page.Paginated[model.Session]); ok {
		r0 = returnFunc(ctx, clientCode, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.Session])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *filter.Options[model.Session]) error); ok {
		r1 = returnFunc(ctx, clientCode, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionRepository_FilterInClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterInClient'
type MockISessionRepository_FilterInClient_Call struct {
	*mock.Call
}

// FilterInClient is a helper method to define mock.On call
//   - ctx context.Context
//   - clientCode string
//   - filter1 *filter.Options[model.Session]
func (_e *MockISessionRepository_Expecter) FilterInClient(ctx any, clientCode any, filter1 any) *MockISessionRepository_FilterInClient_Call {
	return &MockISessionRepository_FilterInClient_Call{Call: _e.mock.On("FilterInClient", ctx, clientCode, filter1)}
}

func (_c *MockISessionRepository_FilterInClient_Call) Run(run func(ctx context.Context, clientCode string, filter1 *filter.Options[model.Session])) *MockISessionRepository_FilterInClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *filter.Options[model.Session]
		if args[2] != nil {
			arg2 = args[2].(*filter.Options[model.Session])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockISessionRepository_FilterInClient_Call) Return(paginated *page.Paginated[model.Session], err error) *MockISessionRepository_FilterInClient_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockISessionRepository_FilterInClient_Call) RunAndReturn(run func(ctx context.Context, clientCode string, filter1 *filter.Options[model.Session]) (*page.Paginated[model.Session], error)) *MockISessionRepository_FilterInClient_Call {
	_c.Call.Return(run)
	return _c
}

// FilterInClientWithUser provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) FilterInClientWithUser(ctx context.Context, clientCode string, userID string, filter1 *filter.Options[model.Session]) (*page.Paginated[model.Session], error) {
	ret := _mock.Called(ctx, clientCode, userID, filter1)

	if len(ret) == 0 {
		panic("no return value specified for FilterInClientWithUser")
	}

	var r0 *page.Paginated[model.Session]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *filter.Options[model.Session]) (*page.Paginated[model.Session], error)); ok {
		return returnFunc(ctx, clientCode, userID, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *filter.Options[model.Session]) *page.Paginated[model.Session]); ok {
		r0 = returnFunc(ctx, clientCode, userID, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.Session])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *filter.Options[model.Session]) error); ok {
		r1 = returnFunc(ctx, clientCode, userID, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionRepository_FilterInClientWithUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterInClientWithUser'
type MockISessionRepository_FilterInClientWithUser_Call struct {
	*mock.Call
}

// FilterInClientWithUser is a helper method to define mock.On call
//   - ctx context.Context
//   - clientCode string
//   - userID string
//   - filter1 *filter.Options[model.Session]
func (_e *MockISessionRepository_Expecter) FilterInClientWithUser(ctx any, clientCode any, userID any, filter1 any) *MockISessionRepository_FilterInClientWithUser_Call {
	return &MockISessionRepository_FilterInClientWithUser_Call{Call: _e.mock.On("FilterInClientWithUser", ctx, clientCode, userID, filter1)}
}

func (_c *MockISessionRepository_FilterInClientWithUser_Call) Run(run func(ctx context.Context, clientCode string, userID string, filter1 *filter.Options[model.Session])) *MockISessionRepository_FilterInClientWithUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *filter.Options[model.Session]
		if args[3] != nil {
			arg3 = args[3].(*filter.Options[model.Session])
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockISessionRepository_FilterInClientWithUser_Call) Return(paginated *page.Paginated[model.Session], err error) *MockISessionRepository_FilterInClientWithUser_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockISessionRepository_FilterInClientWithUser_Call) RunAndReturn(run func(ctx context.Context, clientCode string, userID string, filter1 *filter.Options[model.Session]) (*page.Paginated[model.Session], error)) *MockISessionRepository_FilterInClientWithUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDInClient provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) FindByIDInClient(ctx context.Context, clientCode string, id string) (*model.Session, error) {
	ret := _mock.Called(ctx, clientCode, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDInClient")
	}

	var r0 *model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Session, error)); ok {
		return returnFunc(ctx, clientCode, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Session); ok {
		r0 = returnFunc(ctx, clientCode, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, clientCode, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionRepository_FindByIDInClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDInClient'
type MockISessionRepository_FindByIDInClient_Call struct {
	*mock.Call
}

// FindByIDInClient is a helper method to define mock.On call
//   - ctx context.Context
//   - clientCode string
//   - id string
func (_e *MockISessionRepository_Expecter) FindByIDInClient(ctx any, clientCode any, id any) *MockISessionRepository_FindByIDInClient_Call {
	return &MockISessionRepository_FindByIDInClient_Call{Call: _e.mock.On("FindByIDInClient", ctx, clientCode, id)}
}

func (_c *MockISessionRepository_FindByIDInClient_Call) Run(run func(ctx context.Context, clientCode string, id string)) *MockISessionRepository_FindByIDInClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockISessionRepository_FindByIDInClient_Call) Return(session *model.Session, err error) *MockISessionRepository_FindByIDInClient_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockISessionRepository_FindByIDInClient_Call) RunAndReturn(run func(ctx context.Context, clientCode string, id string) (*model.Session, error)) *MockISessionRepository_FindByIDInClient_Call {
	_c.Call.Return(run)
	return _c
}
