// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockISessionRepository creates a new instance of MockISessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISessionRepository {
	mock := &MockISessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockISessionRepository is an autogenerated mock type for the ISessionRepository type
type MockISessionRepository struct {
	mock.Mock
}

type MockISessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISessionRepository) EXPECT() *MockISessionRepository_Expecter {
	return &MockISessionRepository_Expecter{mock: &_m.Mock}
}

// CheckUserAccess provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) CheckUserAccess(ctx context.Context, appID string, userID string, sessionID string) (bool, error) {
	ret := _mock.Called(ctx, appID, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserAccess")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, appID, userID, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, appID, userID, sessionID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, appID, userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionRepository_CheckUserAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserAccess'
type MockISessionRepository_CheckUserAccess_Call struct {
	*mock.Call
}

// CheckUserAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - userID string
//   - sessionID string
func (_e *MockISessionRepository_Expecter) CheckUserAccess(ctx any, appID any, userID any, sessionID any) *MockISessionRepository_CheckUserAccess_Call {
	return &MockISessionRepository_CheckUserAccess_Call{Call: _e.mock.On("CheckUserAccess", ctx, appID, userID, sessionID)}
}

func (_c *MockISessionRepository_CheckUserAccess_Call) Run(run func(ctx context.Context, appID string, userID string, sessionID string)) *MockISessionRepository_CheckUserAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockISessionRepository_CheckUserAccess_Call) Return(b bool, err error) *MockISessionRepository_CheckUserAccess_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockISessionRepository_CheckUserAccess_Call) RunAndReturn(run func(ctx context.Context, appID string, userID string, sessionID string) (bool, error)) *MockISessionRepository_CheckUserAccess_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) Create(ctx context.Context, model1 *model.Session) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Session) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockISessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockISessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.Session
func (_e *MockISessionRepository_Expecter) Create(ctx any, model1 any) *MockISessionRepository_Create_Call {
	return &MockISessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockISessionRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.Session)) *MockISessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Session
		if args[1] != nil {
			arg1 = args[1].(*model.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISessionRepository_Create_Call) Return(err error) *MockISessionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockISessionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.Session) error) *MockISessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockISessionRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockISessionRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockISessionRepository_Expecter) DeleteByID(ctx any, id any) *MockISessionRepository_DeleteByID_Call {
	return &MockISessionRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockISessionRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockISessionRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISessionRepository_DeleteByID_Call) Return(err error) *MockISessionRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockISessionRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockISessionRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInApp provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) DeleteInApp(ctx context.Context, appID string, ID string) error {
	ret := _mock.Called(ctx, appID, ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInApp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, appID, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockISessionRepository_DeleteInApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInApp'
type MockISessionRepository_DeleteInApp_Call struct {
	*mock.Call
}

// DeleteInApp is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - ID string
func (_e *MockISessionRepository_Expecter) DeleteInApp(ctx any, appID any, ID any) *MockISessionRepository_DeleteInApp_Call {
	return &MockISessionRepository_DeleteInApp_Call{Call: _e.mock.On("DeleteInApp", ctx, appID, ID)}
}

func (_c *MockISessionRepository_DeleteInApp_Call) Run(run func(ctx context.Context, appID string, ID string)) *MockISessionRepository_DeleteInApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockISessionRepository_DeleteInApp_Call) Return(err error) *MockISessionRepository_DeleteInApp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockISessionRepository_DeleteInApp_Call) RunAndReturn(run func(ctx context.Context, appID string, ID string) error) *MockISessionRepository_DeleteInApp_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) Filter(ctx context.Context, filter1 *filter.Options[model.Session]) (*page.Paginated[model.Session], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.Session]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.Session]) (*page.Paginated[model.Session], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.Session]) *page.Paginated[model.Session]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.Session])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.Session]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockISessionRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.Session]
func (_e *MockISessionRepository_Expecter) Filter(ctx any, filter1 any) *MockISessionRepository_Filter_Call {
	return &MockISessionRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockISessionRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.Session])) *MockISessionRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.Session]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.Session])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISessionRepository_Filter_Call) Return(paginated *page.Paginated[model.Session], err error) *MockISessionRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockISessionRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.Session]) (*page.Paginated[model.Session], error)) *MockISessionRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FilterInApp provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) FilterInApp(ctx context.Context, appID string, filter1 *filter.Options[model.Session]) (*page.Paginated[model.Session], error) {
	ret := _mock.Called(ctx, appID, filter1)

	if len(ret) == 0 {
		panic("no return value specified for FilterInApp")
	}

	var r0 *page.Paginated[model.Session]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *filter.Options[model.Session]) (*page.Paginated[model.Session], error)); ok {
		return returnFunc(ctx, appID, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *filter.Options[model.Session]) *page.Paginated[model.Session]); ok {
		r0 = returnFunc(ctx, appID, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.Session])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *filter.Options[model.Session]) error); ok {
		r1 = returnFunc(ctx, appID, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionRepository_FilterInApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterInApp'
type MockISessionRepository_FilterInApp_Call struct {
	*mock.Call
}

// FilterInApp is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - filter1 *filter.Options[model.Session]
func (_e *MockISessionRepository_Expecter) FilterInApp(ctx any, appID any, filter1 any) *MockISessionRepository_FilterInApp_Call {
	return &MockISessionRepository_FilterInApp_Call{Call: _e.mock.On("FilterInApp", ctx, appID, filter1)}
}

func (_c *MockISessionRepository_FilterInApp_Call) Run(run func(ctx context.Context, appID string, filter1 *filter.Options[model.Session])) *MockISessionRepository_FilterInApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *filter.Options[model.Session]
		if args[2] != nil {
			arg2 = args[2].(*filter.Options[model.Session])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockISessionRepository_FilterInApp_Call) Return(paginated *page.Paginated[model.Session], err error) *MockISessionRepository_FilterInApp_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockISessionRepository_FilterInApp_Call) RunAndReturn(run func(ctx context.Context, appID string, filter1 *filter.Options[model.Session]) (*page.Paginated[model.Session], error)) *MockISessionRepository_FilterInApp_Call {
	_c.Call.Return(run)
	return _c
}

// FilterInAppWithUser provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) FilterInAppWithUser(ctx context.Context, appID string, userID string, filter1 *filter.Options[model.Session]) (*page.Paginated[model.Session], error) {
	ret := _mock.Called(ctx, appID, userID, filter1)

	if len(ret) == 0 {
		panic("no return value specified for FilterInAppWithUser")
	}

	var r0 *page.Paginated[model.Session]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *filter.Options[model.Session]) (*page.Paginated[model.Session], error)); ok {
		return returnFunc(ctx, appID, userID, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *filter.Options[model.Session]) *page.Paginated[model.Session]); ok {
		r0 = returnFunc(ctx, appID, userID, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.Session])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *filter.Options[model.Session]) error); ok {
		r1 = returnFunc(ctx, appID, userID, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionRepository_FilterInAppWithUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterInAppWithUser'
type MockISessionRepository_FilterInAppWithUser_Call struct {
	*mock.Call
}

// FilterInAppWithUser is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - userID string
//   - filter1 *filter.Options[model.Session]
func (_e *MockISessionRepository_Expecter) FilterInAppWithUser(ctx any, appID any, userID any, filter1 any) *MockISessionRepository_FilterInAppWithUser_Call {
	return &MockISessionRepository_FilterInAppWithUser_Call{Call: _e.mock.On("FilterInAppWithUser", ctx, appID, userID, filter1)}
}

func (_c *MockISessionRepository_FilterInAppWithUser_Call) Run(run func(ctx context.Context, appID string, userID string, filter1 *filter.Options[model.Session])) *MockISessionRepository_FilterInAppWithUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *filter.Options[model.Session]
		if args[3] != nil {
			arg3 = args[3].(*filter.Options[model.Session])
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockISessionRepository_FilterInAppWithUser_Call) Return(paginated *page.Paginated[model.Session], err error) *MockISessionRepository_FilterInAppWithUser_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockISessionRepository_FilterInAppWithUser_Call) RunAndReturn(run func(ctx context.Context, appID string, userID string, filter1 *filter.Options[model.Session]) (*page.Paginated[model.Session], error)) *MockISessionRepository_FilterInAppWithUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) FindByID(ctx context.Context, id string) (*model.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockISessionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockISessionRepository_Expecter) FindByID(ctx any, id any) *MockISessionRepository_FindByID_Call {
	return &MockISessionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockISessionRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockISessionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISessionRepository_FindByID_Call) Return(session *model.Session, err error) *MockISessionRepository_FindByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockISessionRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Session, error)) *MockISessionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDInApp provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) FindByIDInApp(ctx context.Context, appID string, id string, opts *filter.Options[model.Session]) (*model.Session, error) {
	ret := _mock.Called(ctx, appID, id, opts)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDInApp")
	}

	var r0 *model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *filter.Options[model.Session]) (*model.Session, error)); ok {
		return returnFunc(ctx, appID, id, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *filter.Options[model.Session]) *model.Session); ok {
		r0 = returnFunc(ctx, appID, id, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *filter.Options[model.Session]) error); ok {
		r1 = returnFunc(ctx, appID, id, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionRepository_FindByIDInApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDInApp'
type MockISessionRepository_FindByIDInApp_Call struct {
	*mock.Call
}

// FindByIDInApp is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - id string
//   - opts *filter.Options[model.Session]
func (_e *MockISessionRepository_Expecter) FindByIDInApp(ctx any, appID any, id any, opts any) *MockISessionRepository_FindByIDInApp_Call {
	return &MockISessionRepository_FindByIDInApp_Call{Call: _e.mock.On("FindByIDInApp", ctx, appID, id, opts)}
}

func (_c *MockISessionRepository_FindByIDInApp_Call) Run(run func(ctx context.Context, appID string, id string, opts *filter.Options[model.Session])) *MockISessionRepository_FindByIDInApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *filter.Options[model.Session]
		if args[3] != nil {
			arg3 = args[3].(*filter.Options[model.Session])
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockISessionRepository_FindByIDInApp_Call) Return(session *model.Session, err error) *MockISessionRepository_FindByIDInApp_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockISessionRepository_FindByIDInApp_Call) RunAndReturn(run func(ctx context.Context, appID string, id string, opts *filter.Options[model.Session]) (*model.Session, error)) *MockISessionRepository_FindByIDInApp_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockISessionRepository
func (_mock *MockISessionRepository) UpdateByID(ctx context.Context, id string, model1 *model.Session) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.Session) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockISessionRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockISessionRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.Session
func (_e *MockISessionRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockISessionRepository_UpdateByID_Call {
	return &MockISessionRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockISessionRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.Session)) *MockISessionRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.Session
		if args[2] != nil {
			arg2 = args[2].(*model.Session)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockISessionRepository_UpdateByID_Call) Return(err error) *MockISessionRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockISessionRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.Session) error) *MockISessionRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
