// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockITenantInvitationRepository creates a new instance of MockITenantInvitationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITenantInvitationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITenantInvitationRepository {
	mock := &MockITenantInvitationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITenantInvitationRepository is an autogenerated mock type for the ITenantInvitationRepository type
type MockITenantInvitationRepository struct {
	mock.Mock
}

type MockITenantInvitationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITenantInvitationRepository) EXPECT() *MockITenantInvitationRepository_Expecter {
	return &MockITenantInvitationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockITenantInvitationRepository
func (_mock *MockITenantInvitationRepository) Create(ctx context.Context, model1 *model.TenantInvitation) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.TenantInvitation) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITenantInvitationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockITenantInvitationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.TenantInvitation
func (_e *MockITenantInvitationRepository_Expecter) Create(ctx any, model1 any) *MockITenantInvitationRepository_Create_Call {
	return &MockITenantInvitationRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockITenantInvitationRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.TenantInvitation)) *MockITenantInvitationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.TenantInvitation
		if args[1] != nil {
			arg1 = args[1].(*model.TenantInvitation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITenantInvitationRepository_Create_Call) Return(err error) *MockITenantInvitationRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITenantInvitationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.TenantInvitation) error) *MockITenantInvitationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockITenantInvitationRepository
func (_mock *MockITenantInvitationRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITenantInvitationRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockITenantInvitationRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockITenantInvitationRepository_Expecter) DeleteByID(ctx any, id any) *MockITenantInvitationRepository_DeleteByID_Call {
	return &MockITenantInvitationRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockITenantInvitationRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockITenantInvitationRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITenantInvitationRepository_DeleteByID_Call) Return(err error) *MockITenantInvitationRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITenantInvitationRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockITenantInvitationRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockITenantInvitationRepository
func (_mock *MockITenantInvitationRepository) Filter(ctx context.Context, filter1 *filter.Options[model.TenantInvitation]) (*page.Paginated[model.TenantInvitation], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.TenantInvitation]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.TenantInvitation]) (*page.Paginated[model.TenantInvitation], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.TenantInvitation]) *page.Paginated[model.TenantInvitation]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.TenantInvitation])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.TenantInvitation]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITenantInvitationRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockITenantInvitationRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.TenantInvitation]
func (_e *MockITenantInvitationRepository_Expecter) Filter(ctx any, filter1 any) *MockITenantInvitationRepository_Filter_Call {
	return &MockITenantInvitationRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockITenantInvitationRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.TenantInvitation])) *MockITenantInvitationRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.TenantInvitation]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.TenantInvitation])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITenantInvitationRepository_Filter_Call) Return(paginated *page.Paginated[model.TenantInvitation], err error) *MockITenantInvitationRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockITenantInvitationRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.TenantInvitation]) (*page.Paginated[model.TenantInvitation], error)) *MockITenantInvitationRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockITenantInvitationRepository
func (_mock *MockITenantInvitationRepository) FindByID(ctx context.Context, id string) (*model.TenantInvitation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.TenantInvitation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.TenantInvitation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.TenantInvitation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantInvitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITenantInvitationRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockITenantInvitationRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockITenantInvitationRepository_Expecter) FindByID(ctx any, id any) *MockITenantInvitationRepository_FindByID_Call {
	return &MockITenantInvitationRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockITenantInvitationRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockITenantInvitationRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITenantInvitationRepository_FindByID_Call) Return(tenantInvitation *model.TenantInvitation, err error) *MockITenantInvitationRepository_FindByID_Call {
	_c.Call.Return(tenantInvitation, err)
	return _c
}

func (_c *MockITenantInvitationRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.TenantInvitation, error)) *MockITenantInvitationRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingByEmailAndTenant provides a mock function for the type MockITenantInvitationRepository
func (_mock *MockITenantInvitationRepository) FindPendingByEmailAndTenant(ctx context.Context, email string, tenantID string) (*model.TenantInvitation, error) {
	ret := _mock.Called(ctx, email, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingByEmailAndTenant")
	}

	var r0 *model.TenantInvitation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.TenantInvitation, error)); ok {
		return returnFunc(ctx, email, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.TenantInvitation); ok {
		r0 = returnFunc(ctx, email, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantInvitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITenantInvitationRepository_FindPendingByEmailAndTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingByEmailAndTenant'
type MockITenantInvitationRepository_FindPendingByEmailAndTenant_Call struct {
	*mock.Call
}

// FindPendingByEmailAndTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - tenantID string
func (_e *MockITenantInvitationRepository_Expecter) FindPendingByEmailAndTenant(ctx any, email any, tenantID any) *MockITenantInvitationRepository_FindPendingByEmailAndTenant_Call {
	return &MockITenantInvitationRepository_FindPendingByEmailAndTenant_Call{Call: _e.mock.On("FindPendingByEmailAndTenant", ctx, email, tenantID)}
}

func (_c *MockITenantInvitationRepository_FindPendingByEmailAndTenant_Call) Run(run func(ctx context.Context, email string, tenantID string)) *MockITenantInvitationRepository_FindPendingByEmailAndTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockITenantInvitationRepository_FindPendingByEmailAndTenant_Call) Return(tenantInvitation *model.TenantInvitation, err error) *MockITenantInvitationRepository_FindPendingByEmailAndTenant_Call {
	_c.Call.Return(tenantInvitation, err)
	return _c
}

func (_c *MockITenantInvitationRepository_FindPendingByEmailAndTenant_Call) RunAndReturn(run func(ctx context.Context, email string, tenantID string) (*model.TenantInvitation, error)) *MockITenantInvitationRepository_FindPendingByEmailAndTenant_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockITenantInvitationRepository
func (_mock *MockITenantInvitationRepository) UpdateByID(ctx context.Context, id string, model1 *model.TenantInvitation) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.TenantInvitation) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITenantInvitationRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockITenantInvitationRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.TenantInvitation
func (_e *MockITenantInvitationRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockITenantInvitationRepository_UpdateByID_Call {
	return &MockITenantInvitationRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockITenantInvitationRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.TenantInvitation)) *MockITenantInvitationRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.TenantInvitation
		if args[2] != nil {
			arg2 = args[2].(*model.TenantInvitation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockITenantInvitationRepository_UpdateByID_Call) Return(err error) *MockITenantInvitationRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITenantInvitationRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.TenantInvitation) error) *MockITenantInvitationRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
