// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIUserRepository creates a new instance of MockIUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserRepository {
	mock := &MockIUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserRepository is an autogenerated mock type for the IUserRepository type
type MockIUserRepository struct {
	mock.Mock
}

type MockIUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserRepository) EXPECT() *MockIUserRepository_Expecter {
	return &MockIUserRepository_Expecter{mock: &_m.Mock}
}

// CreateInClient provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) CreateInClient(ctx context.Context, clientCode string, user *model.ClientUser, externalID *string) error {
	ret := _mock.Called(ctx, clientCode, user, externalID)

	if len(ret) == 0 {
		panic("no return value specified for CreateInClient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ClientUser, *string) error); ok {
		r0 = returnFunc(ctx, clientCode, user, externalID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_CreateInClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInClient'
type MockIUserRepository_CreateInClient_Call struct {
	*mock.Call
}

// CreateInClient is a helper method to define mock.On call
//   - ctx context.Context
//   - clientCode string
//   - user *model.User
//   - externalID *string
func (_e *MockIUserRepository_Expecter) CreateInClient(ctx any, clientCode any, user any, externalID any) *MockIUserRepository_CreateInClient_Call {
	return &MockIUserRepository_CreateInClient_Call{Call: _e.mock.On("CreateInClient", ctx, clientCode, user, externalID)}
}

func (_c *MockIUserRepository_CreateInClient_Call) Run(run func(ctx context.Context, clientCode string, user *model.ClientUser, externalID *string)) *MockIUserRepository_CreateInClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.ClientUser
		if args[2] != nil {
			arg2 = args[2].(*model.ClientUser)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIUserRepository_CreateInClient_Call) Return(err error) *MockIUserRepository_CreateInClient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_CreateInClient_Call) RunAndReturn(run func(ctx context.Context, clientCode string, user *model.ClientUser, externalID *string) error) *MockIUserRepository_CreateInClient_Call {
	_c.Call.Return(run)
	return _c
}

// FilterInClient provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) FilterInClient(ctx context.Context, clientCode string, filter1 *filter.Options[model.ClientUser]) (*page.Paginated[model.ClientUser], error) {
	ret := _mock.Called(ctx, clientCode, filter1)

	if len(ret) == 0 {
		panic("no return value specified for FilterInClient")
	}

	var r0 *page.Paginated[model.ClientUser]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *filter.Options[model.ClientUser]) (*page.Paginated[model.ClientUser], error)); ok {
		return returnFunc(ctx, clientCode, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *filter.Options[model.ClientUser]) *page.Paginated[model.ClientUser]); ok {
		r0 = returnFunc(ctx, clientCode, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.ClientUser])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *filter.Options[model.ClientUser]) error); ok {
		r1 = returnFunc(ctx, clientCode, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_FilterInClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterInClient'
type MockIUserRepository_FilterInClient_Call struct {
	*mock.Call
}

// FilterInClient is a helper method to define mock.On call
//   - ctx context.Context
//   - clientCode string
//   - filter1 *filter.Options[model.ClientUser]
func (_e *MockIUserRepository_Expecter) FilterInClient(ctx any, clientCode any, filter1 any) *MockIUserRepository_FilterInClient_Call {
	return &MockIUserRepository_FilterInClient_Call{Call: _e.mock.On("FilterInClient", ctx, clientCode, filter1)}
}

func (_c *MockIUserRepository_FilterInClient_Call) Run(run func(ctx context.Context, clientCode string, filter1 *filter.Options[model.ClientUser])) *MockIUserRepository_FilterInClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *filter.Options[model.ClientUser]
		if args[2] != nil {
			arg2 = args[2].(*filter.Options[model.ClientUser])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserRepository_FilterInClient_Call) Return(paginated *page.Paginated[model.ClientUser], err error) *MockIUserRepository_FilterInClient_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIUserRepository_FilterInClient_Call) RunAndReturn(run func(ctx context.Context, clientCode string, filter1 *filter.Options[model.ClientUser]) (*page.Paginated[model.ClientUser], error)) *MockIUserRepository_FilterInClient_Call {
	_c.Call.Return(run)
	return _c
}

// FindByExternalIDInClient provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) FindByExternalIDInClient(ctx context.Context, clientCode string, externalID string) (*model.ClientUser, error) {
	ret := _mock.Called(ctx, clientCode, externalID)

	if len(ret) == 0 {
		panic("no return value specified for FindByExternalIDInClient")
	}

	var r0 *model.ClientUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.ClientUser, error)); ok {
		return returnFunc(ctx, clientCode, externalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.ClientUser); ok {
		r0 = returnFunc(ctx, clientCode, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClientUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, clientCode, externalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_FindByExternalIDInClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByExternalIDInClient'
type MockIUserRepository_FindByExternalIDInClient_Call struct {
	*mock.Call
}

// FindByExternalIDInClient is a helper method to define mock.On call
//   - ctx context.Context
//   - clientCode string
//   - externalID string
func (_e *MockIUserRepository_Expecter) FindByExternalIDInClient(ctx any, clientCode any, externalID any) *MockIUserRepository_FindByExternalIDInClient_Call {
	return &MockIUserRepository_FindByExternalIDInClient_Call{Call: _e.mock.On("FindByExternalIDInClient", ctx, clientCode, externalID)}
}

func (_c *MockIUserRepository_FindByExternalIDInClient_Call) Run(run func(ctx context.Context, clientCode string, externalID string)) *MockIUserRepository_FindByExternalIDInClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserRepository_FindByExternalIDInClient_Call) Return(user *model.ClientUser, err error) *MockIUserRepository_FindByExternalIDInClient_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_FindByExternalIDInClient_Call) RunAndReturn(run func(ctx context.Context, clientCode string, externalID string) (*model.ClientUser, error)) *MockIUserRepository_FindByExternalIDInClient_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDInClient provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) FindByIDInClient(ctx context.Context, clientCode string, id string) (*model.ClientUser, error) {
	ret := _mock.Called(ctx, clientCode, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDInClient")
	}

	var r0 *model.ClientUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.ClientUser, error)); ok {
		return returnFunc(ctx, clientCode, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.ClientUser); ok {
		r0 = returnFunc(ctx, clientCode, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClientUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, clientCode, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_FindByIDInClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDInClient'
type MockIUserRepository_FindByIDInClient_Call struct {
	*mock.Call
}

// FindByIDInClient is a helper method to define mock.On call
//   - ctx context.Context
//   - clientCode string
//   - id string
func (_e *MockIUserRepository_Expecter) FindByIDInClient(ctx any, clientCode any, id any) *MockIUserRepository_FindByIDInClient_Call {
	return &MockIUserRepository_FindByIDInClient_Call{Call: _e.mock.On("FindByIDInClient", ctx, clientCode, id)}
}

func (_c *MockIUserRepository_FindByIDInClient_Call) Run(run func(ctx context.Context, clientCode string, id string)) *MockIUserRepository_FindByIDInClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserRepository_FindByIDInClient_Call) Return(user *model.ClientUser, err error) *MockIUserRepository_FindByIDInClient_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_FindByIDInClient_Call) RunAndReturn(run func(ctx context.Context, clientCode string, id string) (*model.ClientUser, error)) *MockIUserRepository_FindByIDInClient_Call {
	_c.Call.Return(run)
	return _c
}
