// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/util"
	"github.com/usesnipet/snipet/pkg/driver"
	"github.com/usesnipet/snipet/pkg/driver/llm"
	"github.com/usesnipet/snipet/pkg/msg"
)

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

type MockDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriver) EXPECT() *MockDriver_Expecter {
	return &MockDriver_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockDriver
func (_mock *MockDriver) Generate(ctx context.Context, config util.JSONMap, prompt llm.Prompt) (msg.Message, error) {
	ret := _mock.Called(ctx, config, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 msg.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap, llm.Prompt) (msg.Message, error)); ok {
		return returnFunc(ctx, config, prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap, llm.Prompt) msg.Message); ok {
		r0 = returnFunc(ctx, config, prompt)
	} else {
		r0 = ret.Get(0).(msg.Message)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, util.JSONMap, llm.Prompt) error); ok {
		r1 = returnFunc(ctx, config, prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockDriver_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - config util.JSONMap
//   - prompt llm.Prompt
func (_e *MockDriver_Expecter) Generate(ctx any, config any, prompt any) *MockDriver_Generate_Call {
	return &MockDriver_Generate_Call{Call: _e.mock.On("Generate", ctx, config, prompt)}
}

func (_c *MockDriver_Generate_Call) Run(run func(ctx context.Context, config util.JSONMap, prompt llm.Prompt)) *MockDriver_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 util.JSONMap
		if args[1] != nil {
			arg1 = args[1].(util.JSONMap)
		}
		var arg2 llm.Prompt
		if args[2] != nil {
			arg2 = args[2].(llm.Prompt)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDriver_Generate_Call) Return(message msg.Message, err error) *MockDriver_Generate_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockDriver_Generate_Call) RunAndReturn(run func(ctx context.Context, config util.JSONMap, prompt llm.Prompt) (msg.Message, error)) *MockDriver_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockDriver
func (_mock *MockDriver) Info() driver.Info {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 driver.Info
	if returnFunc, ok := ret.Get(0).(func() driver.Info); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(driver.Info)
	}
	return r0
}

// MockDriver_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockDriver_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockDriver_Expecter) Info() *MockDriver_Info_Call {
	return &MockDriver_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockDriver_Info_Call) Run(run func()) *MockDriver_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriver_Info_Call) Return(info driver.Info) *MockDriver_Info_Call {
	_c.Call.Return(info)
	return _c
}

func (_c *MockDriver_Info_Call) RunAndReturn(run func() driver.Info) *MockDriver_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Stream provides a mock function for the type MockDriver
func (_mock *MockDriver) Stream(ctx context.Context, config util.JSONMap, prompt llm.Prompt) (<-chan llm.StreamDelta, error) {
	ret := _mock.Called(ctx, config, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 <-chan llm.StreamDelta
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap, llm.Prompt) (<-chan llm.StreamDelta, error)); ok {
		return returnFunc(ctx, config, prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap, llm.Prompt) <-chan llm.StreamDelta); ok {
		r0 = returnFunc(ctx, config, prompt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan llm.StreamDelta)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, util.JSONMap, llm.Prompt) error); ok {
		r1 = returnFunc(ctx, config, prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type MockDriver_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - ctx context.Context
//   - config util.JSONMap
//   - prompt llm.Prompt
func (_e *MockDriver_Expecter) Stream(ctx any, config any, prompt any) *MockDriver_Stream_Call {
	return &MockDriver_Stream_Call{Call: _e.mock.On("Stream", ctx, config, prompt)}
}

func (_c *MockDriver_Stream_Call) Run(run func(ctx context.Context, config util.JSONMap, prompt llm.Prompt)) *MockDriver_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 util.JSONMap
		if args[1] != nil {
			arg1 = args[1].(util.JSONMap)
		}
		var arg2 llm.Prompt
		if args[2] != nil {
			arg2 = args[2].(llm.Prompt)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDriver_Stream_Call) Return(streamDeltaCh <-chan llm.StreamDelta, err error) *MockDriver_Stream_Call {
	_c.Call.Return(streamDeltaCh, err)
	return _c
}

func (_c *MockDriver_Stream_Call) RunAndReturn(run func(ctx context.Context, config util.JSONMap, prompt llm.Prompt) (<-chan llm.StreamDelta, error)) *MockDriver_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type MockDriver
func (_mock *MockDriver) TestConnection(ctx context.Context, config util.JSONMap) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriver_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockDriver_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - config util.JSONMap
func (_e *MockDriver_Expecter) TestConnection(ctx any, config any) *MockDriver_TestConnection_Call {
	return &MockDriver_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx, config)}
}

func (_c *MockDriver_TestConnection_Call) Run(run func(ctx context.Context, config util.JSONMap)) *MockDriver_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 util.JSONMap
		if args[1] != nil {
			arg1 = args[1].(util.JSONMap)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDriver_TestConnection_Call) Return(err error) *MockDriver_TestConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriver_TestConnection_Call) RunAndReturn(run func(ctx context.Context, config util.JSONMap) error) *MockDriver_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}
