// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/riverqueue/river"
	"github.com/riverqueue/river/rivertype"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIJobQueue creates a new instance of MockIJobQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIJobQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIJobQueue {
	mock := &MockIJobQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIJobQueue is an autogenerated mock type for the IJobQueue type
type MockIJobQueue struct {
	mock.Mock
}

type MockIJobQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIJobQueue) EXPECT() *MockIJobQueue_Expecter {
	return &MockIJobQueue_Expecter{mock: &_m.Mock}
}

// JobGet provides a mock function for the type MockIJobQueue
func (_mock *MockIJobQueue) JobGet(ctx context.Context, id int64) (*rivertype.JobRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for JobGet")
	}

	var r0 *rivertype.JobRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*rivertype.JobRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *rivertype.JobRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rivertype.JobRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJobQueue_JobGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobGet'
type MockIJobQueue_JobGet_Call struct {
	*mock.Call
}

// JobGet is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIJobQueue_Expecter) JobGet(ctx any, id any) *MockIJobQueue_JobGet_Call {
	return &MockIJobQueue_JobGet_Call{Call: _e.mock.On("JobGet", ctx, id)}
}

func (_c *MockIJobQueue_JobGet_Call) Run(run func(ctx context.Context, id int64)) *MockIJobQueue_JobGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIJobQueue_JobGet_Call) Return(jobRow *rivertype.JobRow, err error) *MockIJobQueue_JobGet_Call {
	_c.Call.Return(jobRow, err)
	return _c
}

func (_c *MockIJobQueue_JobGet_Call) RunAndReturn(run func(ctx context.Context, id int64) (*rivertype.JobRow, error)) *MockIJobQueue_JobGet_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type MockIJobQueue
func (_mock *MockIJobQueue) Push(ctx context.Context, args river.JobArgs, opts *river.InsertOpts) (int64, error) {
	ret := _mock.Called(ctx, args, opts)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, river.JobArgs, *river.InsertOpts) (int64, error)); ok {
		return returnFunc(ctx, args, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, river.JobArgs, *river.InsertOpts) int64); ok {
		r0 = returnFunc(ctx, args, opts)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, river.JobArgs, *river.InsertOpts) error); ok {
		r1 = returnFunc(ctx, args, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJobQueue_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockIJobQueue_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - args river.JobArgs
//   - opts *river.InsertOpts
func (_e *MockIJobQueue_Expecter) Push(ctx any, args any, opts any) *MockIJobQueue_Push_Call {
	return &MockIJobQueue_Push_Call{Call: _e.mock.On("Push", ctx, args, opts)}
}

func (_c *MockIJobQueue_Push_Call) Run(run func(ctx context.Context, args river.JobArgs, opts *river.InsertOpts)) *MockIJobQueue_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 river.JobArgs
		if args[1] != nil {
			arg1 = args[1].(river.JobArgs)
		}
		var arg2 *river.InsertOpts
		if args[2] != nil {
			arg2 = args[2].(*river.InsertOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIJobQueue_Push_Call) Return(n int64, err error) *MockIJobQueue_Push_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIJobQueue_Push_Call) RunAndReturn(run func(ctx context.Context, args river.JobArgs, opts *river.InsertOpts) (int64, error)) *MockIJobQueue_Push_Call {
	_c.Call.Return(run)
	return _c
}
