// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/util"
	"github.com/usesnipet/snipet/pkg/driver"
	"github.com/usesnipet/snipet/pkg/driver/knowledge"
)

// NewMockIIndexDriver creates a new instance of MockIIndexDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIIndexDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIIndexDriver {
	mock := &MockIIndexDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIIndexDriver is an autogenerated mock type for the IIndexDriver type
type MockIIndexDriver struct {
	mock.Mock
}

type MockIIndexDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIIndexDriver) EXPECT() *MockIIndexDriver_Expecter {
	return &MockIIndexDriver_Expecter{mock: &_m.Mock}
}

// Info provides a mock function for the type MockIIndexDriver
func (_mock *MockIIndexDriver) Info() driver.Info {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 driver.Info
	if returnFunc, ok := ret.Get(0).(func() driver.Info); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(driver.Info)
	}
	return r0
}

// MockIIndexDriver_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockIIndexDriver_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockIIndexDriver_Expecter) Info() *MockIIndexDriver_Info_Call {
	return &MockIIndexDriver_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockIIndexDriver_Info_Call) Run(run func()) *MockIIndexDriver_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIIndexDriver_Info_Call) Return(info driver.Info) *MockIIndexDriver_Info_Call {
	_c.Call.Return(info)
	return _c
}

func (_c *MockIIndexDriver_Info_Call) RunAndReturn(run func() driver.Info) *MockIIndexDriver_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Reader provides a mock function for the type MockIIndexDriver
func (_mock *MockIIndexDriver) Reader(config util.JSONMap) (knowledge.IKnowledgeIndexReader, error) {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Reader")
	}

	var r0 knowledge.IKnowledgeIndexReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(util.JSONMap) (knowledge.IKnowledgeIndexReader, error)); ok {
		return returnFunc(config)
	}
	if returnFunc, ok := ret.Get(0).(func(util.JSONMap) knowledge.IKnowledgeIndexReader); ok {
		r0 = returnFunc(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(knowledge.IKnowledgeIndexReader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(util.JSONMap) error); ok {
		r1 = returnFunc(config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIIndexDriver_Reader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reader'
type MockIIndexDriver_Reader_Call struct {
	*mock.Call
}

// Reader is a helper method to define mock.On call
//   - config util.JSONMap
func (_e *MockIIndexDriver_Expecter) Reader(config any) *MockIIndexDriver_Reader_Call {
	return &MockIIndexDriver_Reader_Call{Call: _e.mock.On("Reader", config)}
}

func (_c *MockIIndexDriver_Reader_Call) Run(run func(config util.JSONMap)) *MockIIndexDriver_Reader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 util.JSONMap
		if args[0] != nil {
			arg0 = args[0].(util.JSONMap)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIIndexDriver_Reader_Call) Return(iKnowledgeIndexReader knowledge.IKnowledgeIndexReader, err error) *MockIIndexDriver_Reader_Call {
	_c.Call.Return(iKnowledgeIndexReader, err)
	return _c
}

func (_c *MockIIndexDriver_Reader_Call) RunAndReturn(run func(config util.JSONMap) (knowledge.IKnowledgeIndexReader, error)) *MockIIndexDriver_Reader_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type MockIIndexDriver
func (_mock *MockIIndexDriver) TestConnection(ctx context.Context, config util.JSONMap) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIIndexDriver_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockIIndexDriver_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - config util.JSONMap
func (_e *MockIIndexDriver_Expecter) TestConnection(ctx any, config any) *MockIIndexDriver_TestConnection_Call {
	return &MockIIndexDriver_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx, config)}
}

func (_c *MockIIndexDriver_TestConnection_Call) Run(run func(ctx context.Context, config util.JSONMap)) *MockIIndexDriver_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 util.JSONMap
		if args[1] != nil {
			arg1 = args[1].(util.JSONMap)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIIndexDriver_TestConnection_Call) Return(err error) *MockIIndexDriver_TestConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIIndexDriver_TestConnection_Call) RunAndReturn(run func(ctx context.Context, config util.JSONMap) error) *MockIIndexDriver_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}

// Writer provides a mock function for the type MockIIndexDriver
func (_mock *MockIIndexDriver) Writer(config util.JSONMap) (knowledge.IKnowledgeIndexWriter, error) {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Writer")
	}

	var r0 knowledge.IKnowledgeIndexWriter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(util.JSONMap) (knowledge.IKnowledgeIndexWriter, error)); ok {
		return returnFunc(config)
	}
	if returnFunc, ok := ret.Get(0).(func(util.JSONMap) knowledge.IKnowledgeIndexWriter); ok {
		r0 = returnFunc(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(knowledge.IKnowledgeIndexWriter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(util.JSONMap) error); ok {
		r1 = returnFunc(config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIIndexDriver_Writer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Writer'
type MockIIndexDriver_Writer_Call struct {
	*mock.Call
}

// Writer is a helper method to define mock.On call
//   - config util.JSONMap
func (_e *MockIIndexDriver_Expecter) Writer(config any) *MockIIndexDriver_Writer_Call {
	return &MockIIndexDriver_Writer_Call{Call: _e.mock.On("Writer", config)}
}

func (_c *MockIIndexDriver_Writer_Call) Run(run func(config util.JSONMap)) *MockIIndexDriver_Writer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 util.JSONMap
		if args[0] != nil {
			arg0 = args[0].(util.JSONMap)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIIndexDriver_Writer_Call) Return(iKnowledgeIndexWriter knowledge.IKnowledgeIndexWriter, err error) *MockIIndexDriver_Writer_Call {
	_c.Call.Return(iKnowledgeIndexWriter, err)
	return _c
}

func (_c *MockIIndexDriver_Writer_Call) RunAndReturn(run func(config util.JSONMap) (knowledge.IKnowledgeIndexWriter, error)) *MockIIndexDriver_Writer_Call {
	_c.Call.Return(run)
	return _c
}
