// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/pkg/driver"
	"github.com/usesnipet/snipet/pkg/driver/knowledge"
	"github.com/usesnipet/snipet/pkg/jsonx"
)

// NewMockISourceDriver creates a new instance of MockISourceDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISourceDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISourceDriver {
	mock := &MockISourceDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockISourceDriver is an autogenerated mock type for the ISourceDriver type
type MockISourceDriver struct {
	mock.Mock
}

type MockISourceDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISourceDriver) EXPECT() *MockISourceDriver_Expecter {
	return &MockISourceDriver_Expecter{mock: &_m.Mock}
}

// Info provides a mock function for the type MockISourceDriver
func (_mock *MockISourceDriver) Info() driver.Info {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 driver.Info
	if returnFunc, ok := ret.Get(0).(func() driver.Info); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(driver.Info)
	}
	return r0
}

// MockISourceDriver_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockISourceDriver_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockISourceDriver_Expecter) Info() *MockISourceDriver_Info_Call {
	return &MockISourceDriver_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockISourceDriver_Info_Call) Run(run func()) *MockISourceDriver_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockISourceDriver_Info_Call) Return(info driver.Info) *MockISourceDriver_Info_Call {
	_c.Call.Return(info)
	return _c
}

func (_c *MockISourceDriver_Info_Call) RunAndReturn(run func() driver.Info) *MockISourceDriver_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Iterator provides a mock function for the type MockISourceDriver
func (_mock *MockISourceDriver) Iterator(ctx context.Context, config jsonx.JSONMap) (knowledge.IKnowledgeIterator, error) {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for Iterator")
	}

	var r0 knowledge.IKnowledgeIterator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, jsonx.JSONMap) (knowledge.IKnowledgeIterator, error)); ok {
		return returnFunc(ctx, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, jsonx.JSONMap) knowledge.IKnowledgeIterator); ok {
		r0 = returnFunc(ctx, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(knowledge.IKnowledgeIterator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, jsonx.JSONMap) error); ok {
		r1 = returnFunc(ctx, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISourceDriver_Iterator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Iterator'
type MockISourceDriver_Iterator_Call struct {
	*mock.Call
}

// Iterator is a helper method to define mock.On call
//   - ctx context.Context
//   - config jsonx.JSONMap
func (_e *MockISourceDriver_Expecter) Iterator(ctx any, config any) *MockISourceDriver_Iterator_Call {
	return &MockISourceDriver_Iterator_Call{Call: _e.mock.On("Iterator", ctx, config)}
}

func (_c *MockISourceDriver_Iterator_Call) Run(run func(ctx context.Context, config jsonx.JSONMap)) *MockISourceDriver_Iterator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 jsonx.JSONMap
		if args[1] != nil {
			arg1 = args[1].(jsonx.JSONMap)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISourceDriver_Iterator_Call) Return(iKnowledgeIterator knowledge.IKnowledgeIterator, err error) *MockISourceDriver_Iterator_Call {
	_c.Call.Return(iKnowledgeIterator, err)
	return _c
}

func (_c *MockISourceDriver_Iterator_Call) RunAndReturn(run func(ctx context.Context, config jsonx.JSONMap) (knowledge.IKnowledgeIterator, error)) *MockISourceDriver_Iterator_Call {
	_c.Call.Return(run)
	return _c
}

// Reader provides a mock function for the type MockISourceDriver
func (_mock *MockISourceDriver) Reader(ctx context.Context, config jsonx.JSONMap, itemID string) (knowledge.IKnowledgeReader, error) {
	ret := _mock.Called(ctx, config, itemID)

	if len(ret) == 0 {
		panic("no return value specified for Reader")
	}

	var r0 knowledge.IKnowledgeReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, jsonx.JSONMap, string) (knowledge.IKnowledgeReader, error)); ok {
		return returnFunc(ctx, config, itemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, jsonx.JSONMap, string) knowledge.IKnowledgeReader); ok {
		r0 = returnFunc(ctx, config, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(knowledge.IKnowledgeReader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, jsonx.JSONMap, string) error); ok {
		r1 = returnFunc(ctx, config, itemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISourceDriver_Reader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reader'
type MockISourceDriver_Reader_Call struct {
	*mock.Call
}

// Reader is a helper method to define mock.On call
//   - ctx context.Context
//   - config jsonx.JSONMap
//   - itemID string
func (_e *MockISourceDriver_Expecter) Reader(ctx any, config any, itemID any) *MockISourceDriver_Reader_Call {
	return &MockISourceDriver_Reader_Call{Call: _e.mock.On("Reader", ctx, config, itemID)}
}

func (_c *MockISourceDriver_Reader_Call) Run(run func(ctx context.Context, config jsonx.JSONMap, itemID string)) *MockISourceDriver_Reader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 jsonx.JSONMap
		if args[1] != nil {
			arg1 = args[1].(jsonx.JSONMap)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockISourceDriver_Reader_Call) Return(iKnowledgeReader knowledge.IKnowledgeReader, err error) *MockISourceDriver_Reader_Call {
	_c.Call.Return(iKnowledgeReader, err)
	return _c
}

func (_c *MockISourceDriver_Reader_Call) RunAndReturn(run func(ctx context.Context, config jsonx.JSONMap, itemID string) (knowledge.IKnowledgeReader, error)) *MockISourceDriver_Reader_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type MockISourceDriver
func (_mock *MockISourceDriver) TestConnection(ctx context.Context, config jsonx.JSONMap) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, jsonx.JSONMap) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockISourceDriver_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockISourceDriver_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - config jsonx.JSONMap
func (_e *MockISourceDriver_Expecter) TestConnection(ctx any, config any) *MockISourceDriver_TestConnection_Call {
	return &MockISourceDriver_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx, config)}
}

func (_c *MockISourceDriver_TestConnection_Call) Run(run func(ctx context.Context, config jsonx.JSONMap)) *MockISourceDriver_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 jsonx.JSONMap
		if args[1] != nil {
			arg1 = args[1].(jsonx.JSONMap)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISourceDriver_TestConnection_Call) Return(err error) *MockISourceDriver_TestConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockISourceDriver_TestConnection_Call) RunAndReturn(run func(ctx context.Context, config jsonx.JSONMap) error) *MockISourceDriver_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockISourceDriver
func (_mock *MockISourceDriver) Validate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockISourceDriver_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockISourceDriver_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *MockISourceDriver_Expecter) Validate() *MockISourceDriver_Validate_Call {
	return &MockISourceDriver_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *MockISourceDriver_Validate_Call) Run(run func()) *MockISourceDriver_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockISourceDriver_Validate_Call) Return(err error) *MockISourceDriver_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockISourceDriver_Validate_Call) RunAndReturn(run func() error) *MockISourceDriver_Validate_Call {
	_c.Call.Return(run)
	return _c
}
