// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/runtime/driver"
	"github.com/usesnipet/snipet/internal/util"
)

// NewMockIKnowledgeIndex creates a new instance of MockIKnowledgeIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIKnowledgeIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIKnowledgeIndex {
	mock := &MockIKnowledgeIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIKnowledgeIndex is an autogenerated mock type for the IKnowledgeIndex type
type MockIKnowledgeIndex struct {
	mock.Mock
}

type MockIKnowledgeIndex_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIKnowledgeIndex) EXPECT() *MockIKnowledgeIndex_Expecter {
	return &MockIKnowledgeIndex_Expecter{mock: &_m.Mock}
}

// Info provides a mock function for the type MockIKnowledgeIndex
func (_mock *MockIKnowledgeIndex) Info() driver.Info {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 driver.Info
	if returnFunc, ok := ret.Get(0).(func() driver.Info); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(driver.Info)
	}
	return r0
}

// MockIKnowledgeIndex_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockIKnowledgeIndex_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockIKnowledgeIndex_Expecter) Info() *MockIKnowledgeIndex_Info_Call {
	return &MockIKnowledgeIndex_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockIKnowledgeIndex_Info_Call) Run(run func()) *MockIKnowledgeIndex_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIKnowledgeIndex_Info_Call) Return(info driver.Info) *MockIKnowledgeIndex_Info_Call {
	_c.Call.Return(info)
	return _c
}

func (_c *MockIKnowledgeIndex_Info_Call) RunAndReturn(run func() driver.Info) *MockIKnowledgeIndex_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Reader provides a mock function for the type MockIKnowledgeIndex
func (_mock *MockIKnowledgeIndex) Reader(config util.JSONMap) (driver.IKnowledgeIndexReader, error) {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Reader")
	}

	var r0 driver.IKnowledgeIndexReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(util.JSONMap) (driver.IKnowledgeIndexReader, error)); ok {
		return returnFunc(config)
	}
	if returnFunc, ok := ret.Get(0).(func(util.JSONMap) driver.IKnowledgeIndexReader); ok {
		r0 = returnFunc(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.IKnowledgeIndexReader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(util.JSONMap) error); ok {
		r1 = returnFunc(config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIKnowledgeIndex_Reader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reader'
type MockIKnowledgeIndex_Reader_Call struct {
	*mock.Call
}

// Reader is a helper method to define mock.On call
//   - config util.JSONMap
func (_e *MockIKnowledgeIndex_Expecter) Reader(config any) *MockIKnowledgeIndex_Reader_Call {
	return &MockIKnowledgeIndex_Reader_Call{Call: _e.mock.On("Reader", config)}
}

func (_c *MockIKnowledgeIndex_Reader_Call) Run(run func(config util.JSONMap)) *MockIKnowledgeIndex_Reader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 util.JSONMap
		if args[0] != nil {
			arg0 = args[0].(util.JSONMap)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIKnowledgeIndex_Reader_Call) Return(iKnowledgeIndexReader driver.IKnowledgeIndexReader, err error) *MockIKnowledgeIndex_Reader_Call {
	_c.Call.Return(iKnowledgeIndexReader, err)
	return _c
}

func (_c *MockIKnowledgeIndex_Reader_Call) RunAndReturn(run func(config util.JSONMap) (driver.IKnowledgeIndexReader, error)) *MockIKnowledgeIndex_Reader_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type MockIKnowledgeIndex
func (_mock *MockIKnowledgeIndex) TestConnection(ctx context.Context, config util.JSONMap) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIKnowledgeIndex_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockIKnowledgeIndex_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - config util.JSONMap
func (_e *MockIKnowledgeIndex_Expecter) TestConnection(ctx any, config any) *MockIKnowledgeIndex_TestConnection_Call {
	return &MockIKnowledgeIndex_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx, config)}
}

func (_c *MockIKnowledgeIndex_TestConnection_Call) Run(run func(ctx context.Context, config util.JSONMap)) *MockIKnowledgeIndex_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 util.JSONMap
		if args[1] != nil {
			arg1 = args[1].(util.JSONMap)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIKnowledgeIndex_TestConnection_Call) Return(err error) *MockIKnowledgeIndex_TestConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIKnowledgeIndex_TestConnection_Call) RunAndReturn(run func(ctx context.Context, config util.JSONMap) error) *MockIKnowledgeIndex_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}

// Writer provides a mock function for the type MockIKnowledgeIndex
func (_mock *MockIKnowledgeIndex) Writer(config util.JSONMap) (driver.IKnowledgeIndexWriter, error) {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Writer")
	}

	var r0 driver.IKnowledgeIndexWriter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(util.JSONMap) (driver.IKnowledgeIndexWriter, error)); ok {
		return returnFunc(config)
	}
	if returnFunc, ok := ret.Get(0).(func(util.JSONMap) driver.IKnowledgeIndexWriter); ok {
		r0 = returnFunc(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.IKnowledgeIndexWriter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(util.JSONMap) error); ok {
		r1 = returnFunc(config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIKnowledgeIndex_Writer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Writer'
type MockIKnowledgeIndex_Writer_Call struct {
	*mock.Call
}

// Writer is a helper method to define mock.On call
//   - config util.JSONMap
func (_e *MockIKnowledgeIndex_Expecter) Writer(config any) *MockIKnowledgeIndex_Writer_Call {
	return &MockIKnowledgeIndex_Writer_Call{Call: _e.mock.On("Writer", config)}
}

func (_c *MockIKnowledgeIndex_Writer_Call) Run(run func(config util.JSONMap)) *MockIKnowledgeIndex_Writer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 util.JSONMap
		if args[0] != nil {
			arg0 = args[0].(util.JSONMap)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIKnowledgeIndex_Writer_Call) Return(iKnowledgeIndexWriter driver.IKnowledgeIndexWriter, err error) *MockIKnowledgeIndex_Writer_Call {
	_c.Call.Return(iKnowledgeIndexWriter, err)
	return _c
}

func (_c *MockIKnowledgeIndex_Writer_Call) RunAndReturn(run func(config util.JSONMap) (driver.IKnowledgeIndexWriter, error)) *MockIKnowledgeIndex_Writer_Call {
	_c.Call.Return(run)
	return _c
}
