// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/runtime/driver"
	"github.com/usesnipet/snipet/internal/runtime/message"
	"github.com/usesnipet/snipet/internal/util"
)

// NewMockILLM creates a new instance of MockILLM. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockILLM(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockILLM {
	mock := &MockILLM{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockILLM is an autogenerated mock type for the ILLM type
type MockILLM struct {
	mock.Mock
}

type MockILLM_Expecter struct {
	mock *mock.Mock
}

func (_m *MockILLM) EXPECT() *MockILLM_Expecter {
	return &MockILLM_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockILLM
func (_mock *MockILLM) Generate(ctx context.Context, config util.JSONMap, instructions string, messages []message.Message) (message.Message, error) {
	ret := _mock.Called(ctx, config, instructions, messages)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 message.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap, string, []message.Message) (message.Message, error)); ok {
		return returnFunc(ctx, config, instructions, messages)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap, string, []message.Message) message.Message); ok {
		r0 = returnFunc(ctx, config, instructions, messages)
	} else {
		r0 = ret.Get(0).(message.Message)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, util.JSONMap, string, []message.Message) error); ok {
		r1 = returnFunc(ctx, config, instructions, messages)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILLM_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockILLM_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - config util.JSONMap
//   - instructions string
//   - messages []message.Message
func (_e *MockILLM_Expecter) Generate(ctx any, config any, instructions any, messages any) *MockILLM_Generate_Call {
	return &MockILLM_Generate_Call{Call: _e.mock.On("Generate", ctx, config, instructions, messages)}
}

func (_c *MockILLM_Generate_Call) Run(run func(ctx context.Context, config util.JSONMap, instructions string, messages []message.Message)) *MockILLM_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 util.JSONMap
		if args[1] != nil {
			arg1 = args[1].(util.JSONMap)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []message.Message
		if args[3] != nil {
			arg3 = args[3].([]message.Message)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockILLM_Generate_Call) Return(message1 message.Message, err error) *MockILLM_Generate_Call {
	_c.Call.Return(message1, err)
	return _c
}

func (_c *MockILLM_Generate_Call) RunAndReturn(run func(ctx context.Context, config util.JSONMap, instructions string, messages []message.Message) (message.Message, error)) *MockILLM_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockILLM
func (_mock *MockILLM) Info() driver.Info {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 driver.Info
	if returnFunc, ok := ret.Get(0).(func() driver.Info); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(driver.Info)
	}
	return r0
}

// MockILLM_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockILLM_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockILLM_Expecter) Info() *MockILLM_Info_Call {
	return &MockILLM_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockILLM_Info_Call) Run(run func()) *MockILLM_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockILLM_Info_Call) Return(info driver.Info) *MockILLM_Info_Call {
	_c.Call.Return(info)
	return _c
}

func (_c *MockILLM_Info_Call) RunAndReturn(run func() driver.Info) *MockILLM_Info_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type MockILLM
func (_mock *MockILLM) TestConnection(ctx context.Context, config util.JSONMap) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILLM_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockILLM_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - config util.JSONMap
func (_e *MockILLM_Expecter) TestConnection(ctx any, config any) *MockILLM_TestConnection_Call {
	return &MockILLM_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx, config)}
}

func (_c *MockILLM_TestConnection_Call) Run(run func(ctx context.Context, config util.JSONMap)) *MockILLM_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 util.JSONMap
		if args[1] != nil {
			arg1 = args[1].(util.JSONMap)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILLM_TestConnection_Call) Return(err error) *MockILLM_TestConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILLM_TestConnection_Call) RunAndReturn(run func(ctx context.Context, config util.JSONMap) error) *MockILLM_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}
