// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/runtime/driver"
	"github.com/usesnipet/snipet/internal/runtime/tool"
	"github.com/usesnipet/snipet/internal/util"
)

// NewMockITool creates a new instance of MockITool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITool {
	mock := &MockITool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITool is an autogenerated mock type for the ITool type
type MockITool struct {
	mock.Mock
}

type MockITool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITool) EXPECT() *MockITool_Expecter {
	return &MockITool_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockITool
func (_mock *MockITool) Execute(ctx context.Context, config util.JSONMap, call tool.Call) tool.Result {
	ret := _mock.Called(ctx, config, call)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 tool.Result
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap, tool.Call) tool.Result); ok {
		r0 = returnFunc(ctx, config, call)
	} else {
		r0 = ret.Get(0).(tool.Result)
	}
	return r0
}

// MockITool_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockITool_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - config util.JSONMap
//   - call tool.Call
func (_e *MockITool_Expecter) Execute(ctx any, config any, call any) *MockITool_Execute_Call {
	return &MockITool_Execute_Call{Call: _e.mock.On("Execute", ctx, config, call)}
}

func (_c *MockITool_Execute_Call) Run(run func(ctx context.Context, config util.JSONMap, call tool.Call)) *MockITool_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 util.JSONMap
		if args[1] != nil {
			arg1 = args[1].(util.JSONMap)
		}
		var arg2 tool.Call
		if args[2] != nil {
			arg2 = args[2].(tool.Call)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockITool_Execute_Call) Return(result tool.Result) *MockITool_Execute_Call {
	_c.Call.Return(result)
	return _c
}

func (_c *MockITool_Execute_Call) RunAndReturn(run func(ctx context.Context, config util.JSONMap, call tool.Call) tool.Result) *MockITool_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockITool
func (_mock *MockITool) Info() driver.Info {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 driver.Info
	if returnFunc, ok := ret.Get(0).(func() driver.Info); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(driver.Info)
	}
	return r0
}

// MockITool_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockITool_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockITool_Expecter) Info() *MockITool_Info_Call {
	return &MockITool_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockITool_Info_Call) Run(run func()) *MockITool_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockITool_Info_Call) Return(info driver.Info) *MockITool_Info_Call {
	_c.Call.Return(info)
	return _c
}

func (_c *MockITool_Info_Call) RunAndReturn(run func() driver.Info) *MockITool_Info_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type MockITool
func (_mock *MockITool) TestConnection(ctx context.Context, config util.JSONMap) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, util.JSONMap) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITool_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockITool_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - config util.JSONMap
func (_e *MockITool_Expecter) TestConnection(ctx any, config any) *MockITool_TestConnection_Call {
	return &MockITool_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx, config)}
}

func (_c *MockITool_TestConnection_Call) Run(run func(ctx context.Context, config util.JSONMap)) *MockITool_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 util.JSONMap
		if args[1] != nil {
			arg1 = args[1].(util.JSONMap)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITool_TestConnection_Call) Return(err error) *MockITool_TestConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITool_TestConnection_Call) RunAndReturn(run func(ctx context.Context, config util.JSONMap) error) *MockITool_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}
